######################################################################
# Automatically generated by qmake (2.01a) Do 20. Mai 14:46:21 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += genproc.h \
           GLee.h \
           glwidget.h \
           mainwindow.h \
           mesh.h \
           QMyWindow.h \
           shader_setup.h \
           stdinc.h \
           textfile.h \
           Vector3D.h \
           Vector4D.h
FORMS += mainwindow.ui
SOURCES += genproc.cpp \
           GLee.c \
           glwidget.cpp \
           main.cpp \
           mesh.cpp \
           QMyWindow.cpp \
           shader_setup.cpp \
           textfile.cpp \
           Vector3D.cpp
QT      += opengl
