#version 330 core
out vec4 fragColor;

in vec3 vWorldPos;
in vec3 vNormal;
in float vChainPhase;
in vec2 vQuadUV;

/**
 * @file BioluminescentSiphonophoreChain.frag
 * @brief Renders the billboard sprites generated by
 * BioluminescentSiphonophoreChain.comp as glowing cyan/seafoam-green
 * nectophores, each blended with the slideshow photo sampled from its world
 * position and topped with a racing action-potential pulse wave.
 *
 * audioPhase drives the cyan-to-green colour oscillation per zooid;
 * audioKick brightens the action-potential pulse's hot core; audioChromaHue
 * and the hueP preset both rotate the final hue. time advances the pulse
 * wave that races along the chain (vChainPhase). The sprite's circular
 * falloff comes from vQuadUV (the quad-local coordinate written by the
 * compute kernel, since geom="indirect" draws triangles rather than
 * GL_POINTS so gl_PointCoord is unavailable). Ends with a soft-knee
 * tone-mapping step so loud audio compresses instead of clipping to white.
 */

uniform sampler2D tex0;
uniform sampler2D tex1;
uniform float interpolation;

uniform float audioPhase;
uniform float audioAdvance;
uniform float audioSwell;
uniform float audioLevel;
uniform float audioKick;
uniform float audioCentroid;
uniform float audioValence;
uniform float audioSubBass;
uniform float audioBass;
uniform float audioMid;
uniform float audioHigh;
uniform float audioFlux;
uniform float audioChromaHue;

uniform float chainP;
uniform float pulseP;
uniform float speedP;
uniform float hueP;
uniform float time;

vec3 img(vec2 uv) {
    return (interpolation * texture(tex0, uv) + (1.0 - interpolation) * texture(tex1, uv)).rgb;
}

vec3 hueRot(vec3 c, float a) {
    vec3 k = vec3(0.57735026919);
    float cs = cos(a), sn = sin(a);
    return c * cs + cross(k, c) * sn + k * dot(k, c) * (1.0 - cs);
}

void main() {
    float hue = (hueP > 0.0) ? hueP : 0.0;

    // Sprite profile
    vec2 pt = vQuadUV;   // quad-local [-1,1]; see .vert
    float r2 = dot(pt, pt);
    if (r2 > 1.0) discard;
    float glow = exp(-r2 * 3.5);

    // Photo texture mapping from world coords
    vec2 photoUV = fract(vWorldPos.xy * 0.25 + 0.5);
    vec3 photo = img(photoUV);

    // Bioluminescent siphonophore cyan & seafoam green palette
    vec3 bioCyan = vec3(0.1, 0.9, 1.0);
    vec3 bioGreen = vec3(0.1, 1.0, 0.6);
    vec3 chainColor = mix(bioCyan, bioGreen, sin(vChainPhase * 12.56 + audioPhase) * 0.5 + 0.5);

    // Action potential pulse wave racing along the chain
    float actionPotential = pow(abs(sin(vChainPhase * 25.0 - time * 6.0)), 8.0);

    vec3 col = mix(photo, chainColor, 0.6) * glow;
    col += actionPotential * vec3(1.0, 0.98, 0.9) * glow * (2.0 + audioKick * 3.0);

    if (audioChromaHue != 0.0) col = hueRot(col, audioChromaHue);
    if (hue > 0.001) col = hueRot(col, hue);

    // Catalogue review: soft-knee exposure — hot audio compresses
    // instead of clipping the whole frame to white.
    vec3 _catTone = (col * 2.8) * 0.55;
    _catTone /= 1.0 + 0.35 * max(_catTone.r, max(_catTone.g, _catTone.b));
    fragColor = vec4(_catTone, glow);
}
