#version 330 core
out vec4 fragColor;   ///< The pixel's colour (output).
// KineticMirrorHexagonArray.frag

uniform vec2  resolution;   ///< Size of the render target in pixels.
uniform float time;   ///< Seconds since the program started (never reset; see sceneTime).
uniform sampler2D tex0;   ///< The current photo.
uniform sampler2D tex1;   ///< The next photo (cross-faded in by interpolation).
uniform float interpolation;   ///< Cross-fade between the photos: 1 = tex0, 0 = tex1.

uniform float audioPhase;   ///< Rotation phase driven by the music (integrated, never jumps).
uniform float audioAdvance;   ///< The music's advance: integrated tempo-weighted energy (never jumps, never runs backwards).
uniform float audioSwell;   ///< Slow loudness envelope, 0..1 (seconds).
uniform float audioLevel;   ///< Overall loudness, 0..1.
uniform float audioKick;   ///< Kick-drum envelope, 0..1 (fast attack, short decay).
uniform float audioCentroid;   ///< Spectral centroid (brightness of the sound), 0..1.
uniform float audioValence;   ///< Mood valence: 0 dark .. 1 bright.
uniform float audioSubBass;   ///< Sub-bass band level, 0..1.
uniform float audioBass;   ///< Bass band level, 0..1.
uniform float audioMid;   ///< Mid band level, 0..1.
uniform float audioHigh;   ///< High band level, 0..1.
uniform float audioFlux;   ///< Spectral flux (how fast the spectrum changes), 0..1.
uniform float audioChromaHue;   ///< Hue of the dominant pitch class (radians, unwrapped: continuous).

uniform float hueP;   ///< Hue knob (radians), usually the music's chroma hue plus a rolled offset.

in vec3 vNormal;   ///< Surface normal (from the vertex stage).
in vec2 vTexCoord;   ///< Texture coordinate (from the vertex stage).
in vec4 vColor;

/**
 * @file KineticMirrorHexagonArray.frag
 * @brief Shades one mirror plate of the suspended kinetic hexagon-lattice
 * sculpture generated by KineticMirrorHexagonArray.vert: chrome-tinted
 * reflection of the current photo pair plus a bright neon edge band.
 *
 * The per-plate normal (vNormal) reflects the slideshow texture; a
 * Blinn-Phong specular term catches a fixed sun direction and is driven
 * harder by audioKick, while audioLevel and audioHigh brighten the
 * reflection and edge glow respectively. The final colour is hue-rotated
 * by audioChromaHue plus the hueP preset, matching the wave/tilt/snap
 * kinematics driven by the same audio set in the vertex stage.
 */

/// @brief The photo at a coordinate: the cross-fade of tex0 and tex1.
vec3 img(vec2 uv) {
    return (interpolation * texture(tex0, uv) + (1.0 - interpolation) * texture(tex1, uv)).rgb;
}

/// @brief Rotates a colour's hue by an angle (about the grey axis).
vec3 hueRot(vec3 c, float a) {
    vec3 k = vec3(0.57735026919);
    float cs = cos(a), sn = sin(a);
    return c * cs + cross(k, c) * sn + k * dot(k, c) * (1.0 - cs);
}

/// @brief Entry point of this shader stage (the file description says what it draws).
void main() {
    float hue = (hueP > 0.0) ? hueP : 0.0;

    vec3 N = normalize(vNormal);
    vec3 V = vec3(0.0, 0.0, 1.0);
    vec3 R = reflect(-V, N);

    // Reflected photo texture
    vec2 refUV = R.xy * 0.5 + vec2(0.5);
    vec3 photoRef = img(fract(refUV));

    // Specular sunlight flash
    vec3 L = normalize(vec3(0.5, 0.8, 1.0));
    vec3 H = normalize(L + V);
    float spec = pow(max(dot(N, H), 0.0), 32.0);

    // Hexagonal mirror border
    vec2 b = abs(vTexCoord - vec2(0.5)) * 2.0;
    float border = max(b.x, b.y);
    float edgeMask = smoothstep(0.85, 0.95, border);

    vec3 col = photoRef * (0.8 + 0.4 * audioLevel) * (1.0 - edgeMask * 0.5);
    col += vColor.rgb * edgeMask * (1.2 + 1.5 * audioHigh);
    col += vec3(1.0, 0.98, 0.9) * spec * (1.5 + 2.0 * audioKick);

    col = hueRot(col, audioChromaHue + hue);
    col = pow(col, vec3(0.9));

    fragColor = vec4(col, 1.0);
}
