#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py from Scene2D/ChainLab2D.frag -- stage A, branch 27: Jacobi cn wallpaper
out vec4 fragColor;   ///< The pixel's colour (output).
uniform sampler2D texIn;
uniform int firstPass;
uniform float subV;
uniform vec2 chainOff;   ///< the target viewport's origin (gl_FragCoord of the lab = pass pixel + chainOff)
uniform float bakeSize;  ///< > 0: the chain baked over [0,1]^2 (a lab that reads it at arbitrary points)
uniform sampler2D texStart;  ///< useStart: the chain's input per pixel (xy) and its time offset (z)
uniform int useStart;
uniform float passScale;   ///< the pass grid relative to the frame (chainScale; 0 = 1)
uniform vec2  resolution;   ///< Size of the render target in pixels.
uniform float sceneTime;   ///< Seconds since this scene was activated.
uniform float audioAdvance;   ///< The music's advance: integrated tempo-weighted energy (never jumps, never runs backwards).
uniform float audioPhase;   ///< Rotation phase driven by the music (integrated, never jumps).
uniform float audioSpread;   ///< Spectral spread, 0..1.
uniform float audioSwell;   ///< Slow loudness envelope, 0..1 (seconds).
uniform float speedP;   ///< Speed knob, 0..1.
/// @brief Mirrored repeat of a coordinate into 0..1 (seamless at every edge).
vec2 mirrorUV(vec2 uv) { return 1.0 - abs(fract(uv * 0.5) * 2.0 - 1.0); }
/// @brief The pixel's position, centred and aspect-corrected (y spans -0.5..0.5).
vec2 screenP() { return (gl_FragCoord.xy / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0); }
/// @brief The complex number e^(i a).
vec2 cexpi(float a) { return vec2(cos(a), sin(a)); }
/// @brief Complex multiplication.
vec2 cmul(vec2 a, vec2 b) { return vec2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x); }
/// @brief Complex division.
vec2 cdiv(vec2 a, vec2 b) { return vec2(a.x * b.x + a.y * b.y, a.y * b.x - a.x * b.y) / max(dot(b, b), 1e-8); }
/// @brief Complex cosine.
vec2 ccos(vec2 a) { return vec2(cos(a.x) * cosh(a.y), -sin(a.x) * sinh(a.y)); }
/// @brief Numerator and denominator of the Jacobi cn function via theta series.
void cnTheta(vec2 v, out vec2 N, out vec2 D)
{
    
    float n = floor(v.y / 3.14159265 + 0.5);
    v -= n * vec2(3.14159265, 3.14159265);
    v.x = mod(v.x + 3.14159265, 6.2831853) - 3.14159265;
    const float q14 = 0.4559381, q94 = 0.0008505, q254 = 1.6e-9;   
    const float q1 = 0.0432139, q4 = 3.487e-6;                       
    vec2 th2 = 2.0 * (q14 * ccos(v) + q94 * ccos(3.0 * v) + q254 * ccos(5.0 * v));
    vec2 th4 = vec2(1.0, 0.0) + 2.0 * (-q1 * ccos(2.0 * v) + q4 * ccos(4.0 * v));
    N = th2 * (1.0 - 2.0 * q1 + 2.0 * q4) / (2.0 * (q14 + q94 + q254));   
    D = th4;
}
vec2 tEllipticWall(vec2 uv, vec2 c, float scale, float t)
{
    vec2 z = (uv - c) * scale * 1.8540747;
    vec2 N, D;
    cnTheta(z * 0.8472131, N, D);
    vec2 zeta = cdiv(N, D);
    return c + cmul(zeta, cexpi(t * 0.3)) * 0.3;
}
float gT, gSpread, gRot, gMw;
vec2 gCw, gCt;
uniform float walkHost;   ///< 1 when the app walks this lab's stages (walk uniforms valid).
uniform float tiltP;   ///< Tilt knob, 0..1.
uniform float tiltA;
float chainTiltZ(vec2 q)
{
    float k = smoothstep(0.15, 1.0, tiltP) * 0.6 * (0.55 + 0.45 * clamp(audioSwell, 0.0, 1.0));
    float a = walkHost > 0.5 ? tiltA : 0.011 * sceneTime;
    return k * dot(vec2(cos(a), sin(a)), q);
}
vec2 cls(vec2 uv, float v)
{
    return tEllipticWall(uv, gCw, 2.0 + 2.0 * v, gT);
    return uv;
}

/// @brief Entry point of this shader stage (the file description says what it draws).
void main()
{
    gT = (0.03 + 0.06 * clamp(speedP, 0.0, 1.0)) * sceneTime + 0.25 * audioAdvance;
    gSpread = clamp(audioSpread, 0.0, 1.0);
    gRot = 0.02 * sceneTime + 0.2 * audioPhase;
    gCw = vec2(0.5) + 0.15 * vec2(sin(0.017 * sceneTime), cos(0.013 * sceneTime));
    gCt = vec2(0.5) + vec2(0.22 * sin(0.023 * sceneTime + 0.3 * sin(0.011 * sceneTime)), 0.16 * cos(0.019 * sceneTime));
    if (useStart == 0 && tiltP > 0.0) {       // the time tilt (chainTiltZ): the same shift in every pass of this pixel
        vec2 sp0 = ((gl_FragCoord.xy / (passScale > 0.0 ? passScale : 1.0) + chainOff) / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0);
        float tz = chainTiltZ(bakeSize > 0.0 ? gl_FragCoord.xy / bakeSize * 2.0 - 1.0 : sp0);
        gT += tz; gRot += 0.5 * tz;
    }
    vec4 st = useStart == 1 ? texelFetch(texStart, ivec2(gl_FragCoord.xy), 0) : vec4(0.0);
    gT += 0.3 * st.z;                          // the solid look: the depth along the normal is the chain's time
    gRot += 0.15 * st.z;
    vec2 fc = gl_FragCoord.xy / (passScale > 0.0 ? passScale : 1.0) + chainOff;   // the lab's own pixel position (screenP)
    vec2 sp = (fc / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0);
    vec2 uv0 = useStart == 1 ? st.xy : (bakeSize > 0.0 ? gl_FragCoord.xy / bakeSize : sp * 0.5 + 0.5);
    vec2 uv = firstPass == 1 ? uv0 : mirrorUV(texelFetch(texIn, ivec2(gl_FragCoord.xy), 0).xy);
    fragColor = vec4(cls(uv, subV), 0.0, 1.0);
}

