#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py from Scene2D/ChainLab2D.frag -- stage A, branch 29: Archimedean spiral
out vec4 fragColor;
uniform sampler2D texIn;
uniform int firstPass;
uniform float subV;
uniform vec2 chainOff;   // the target viewport's origin (gl_FragCoord of the lab = pass pixel + chainOff)
uniform float bakeSize;  // > 0: the chain baked over [0,1]^2 (a lab that reads it at arbitrary points)
uniform vec2  resolution;
uniform float sceneTime;
uniform float audioAdvance;
uniform float audioPhase;
uniform float audioSpread;
uniform float speedP;
vec2 mirrorUV(vec2 uv) { return 1.0 - abs(fract(uv * 0.5) * 2.0 - 1.0); }
vec2 screenP() { return (gl_FragCoord.xy / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0); }
vec2 tArchimedes(vec2 uv, vec2 c, float k, float travel)
{
    vec2 d = uv - c;
    float r = length(d) * k, a = atan(d.y, d.x) / 3.14159265;
    return vec2(r - a - travel, r + a);
}
float gT, gSpread, gRot, gMw;
vec2 gCw, gCt;
vec2 cls(vec2 uv, float v)
{
    return tArchimedes(uv, gCt, 4.0 + 6.0 * v, gT * 2.0);
    return uv;
}

void main()
{
    gT = (0.03 + 0.06 * clamp(speedP, 0.0, 1.0)) * sceneTime + 0.25 * audioAdvance;
    gSpread = clamp(audioSpread, 0.0, 1.0);
    gRot = 0.02 * sceneTime + 0.2 * audioPhase;
    gCw = vec2(0.5) + 0.15 * vec2(sin(0.017 * sceneTime), cos(0.013 * sceneTime));
    gCt = vec2(0.5) + vec2(0.22 * sin(0.023 * sceneTime + 0.3 * sin(0.011 * sceneTime)), 0.16 * cos(0.019 * sceneTime));
    vec2 fc = gl_FragCoord.xy + chainOff;     // the lab's own pixel position (screenP)
    vec2 sp = (fc / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0);
    vec2 uv0 = bakeSize > 0.0 ? gl_FragCoord.xy / bakeSize : sp * 0.5 + 0.5;   // bake: the chain over [0,1]^2
    vec2 uv = firstPass == 1 ? uv0 : mirrorUV(texelFetch(texIn, ivec2(gl_FragCoord.xy), 0).xy);
    fragColor = vec4(cls(uv, subV), 0.0, 1.0);
}

