#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py from Scene2D/ChainLab2D.frag -- stage B, branch 19: Pappus chain
out vec4 fragColor;
uniform sampler2D texIn;
uniform int firstPass;
uniform float subV;
uniform vec2 chainOff;   // the target viewport's origin (gl_FragCoord of the lab = pass pixel + chainOff)
uniform float bakeSize;  // > 0: the chain baked over [0,1]^2 (a lab that reads it at arbitrary points)
uniform sampler2D texStart;  // useStart: the chain's input per pixel (xy) and its time offset (z)
uniform int useStart;
uniform float passScale;   // the pass grid relative to the frame (chainScale; 0 = 1)
uniform vec2  resolution;
uniform float sceneTime;
uniform float audioAdvance;
uniform float audioPhase;
uniform float audioSpread;
uniform float audioSwell;
uniform float speedP;
vec2 mirrorUV(vec2 uv) { return 1.0 - abs(fract(uv * 0.5) * 2.0 - 1.0); }
vec2 screenP() { return (gl_FragCoord.xy / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0); }
vec2 tPappus(vec2 uv, vec2 c, float width, float travel)
{
    vec2 p = c + vec2(0.35, 0.0), d = uv - p;
    vec2 w = d / max(dot(d, d), 1e-5);
    w.y = width * (abs(mod(w.y / width - 1.0 + travel, 4.0) - 2.0) - 1.0);
    return p + w / max(dot(w, w), 1e-5) * 0.8;
}
float gT, gSpread, gRot, gMw;
vec2 gCw, gCt;
uniform float tiltP;
float chainTiltZ(vec2 q)
{
    float k = smoothstep(0.15, 1.0, tiltP) * 0.6 * (0.55 + 0.45 * clamp(audioSwell, 0.0, 1.0));
    float a = 0.011 * sceneTime;
    return k * dot(vec2(cos(a), sin(a)), q);
}
vec2 cls(vec2 uv, float v)
{
    return tPappus(uv, gCw, 0.25 + 0.2 * v, gT * 0.5);
    return uv;
}

void main()
{
    gT = (0.03 + 0.06 * clamp(speedP, 0.0, 1.0)) * sceneTime + 0.25 * audioAdvance;
    gSpread = clamp(audioSpread, 0.0, 1.0);
    gRot = 0.02 * sceneTime + 0.2 * audioPhase;
    gCw = vec2(0.5) + 0.15 * vec2(sin(0.017 * sceneTime), cos(0.013 * sceneTime));
    gCt = vec2(0.5) + vec2(0.22 * sin(0.023 * sceneTime + 0.3 * sin(0.011 * sceneTime)), 0.16 * cos(0.019 * sceneTime));
    if (useStart == 0 && tiltP > 0.0) {       // the time tilt (chainTiltZ): the same shift in every pass of this pixel
        vec2 sp0 = ((gl_FragCoord.xy / (passScale > 0.0 ? passScale : 1.0) + chainOff) / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0);
        float tz = chainTiltZ(bakeSize > 0.0 ? gl_FragCoord.xy / bakeSize * 2.0 - 1.0 : sp0);
        gT += tz; gRot += 0.5 * tz;
    }
    vec4 st = useStart == 1 ? texelFetch(texStart, ivec2(gl_FragCoord.xy), 0) : vec4(0.0);
    gT += 0.3 * st.z;                          // the solid look: the depth along the normal is the chain's time
    gRot += 0.15 * st.z;
    vec2 fc = gl_FragCoord.xy / (passScale > 0.0 ? passScale : 1.0) + chainOff;   // the lab's own pixel position (screenP)
    vec2 sp = (fc / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0);
    vec2 uv0 = useStart == 1 ? st.xy : (bakeSize > 0.0 ? gl_FragCoord.xy / bakeSize : sp * 0.5 + 0.5);
    vec2 uv = firstPass == 1 ? uv0 : mirrorUV(texelFetch(texIn, ivec2(gl_FragCoord.xy), 0).xy);
    fragColor = vec4(cls(uv, subV), 0.0, 1.0);
}

