#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py -- the 3D lab's last pass: colour, relief, light and fog from the G-buffer
// @chain3d
out vec4 fragColor;   ///< The pixel's colour (output).
uniform sampler2D texGPos, texGNrm;   // the geometry pass
uniform sampler2D texChain0, texChain1, texChain2;   // the colour chain per projection plane
uniform vec2 chainOff;
uniform vec2  resolution;   ///< Size of the render target in pixels.
uniform float time;   ///< Seconds since the program started (never reset; see sceneTime).
uniform sampler2D tex0;   ///< The current photo.
uniform sampler2D tex1;   ///< The next photo (cross-faded in by interpolation).
uniform float interpolation;   ///< Cross-fade between the photos: 1 = tex0, 0 = tex1.
uniform float sceneTime;   ///< Seconds since this scene was activated.
uniform float sceneAdvance;   ///< The music's advance since this scene was activated (integrated, never jumps).
uniform float audioAdvance;   ///< The music's advance: integrated tempo-weighted energy (never jumps, never runs backwards).
uniform float audioLevel;   ///< Overall loudness, 0..1.
uniform float audioPhase;   ///< Rotation phase driven by the music (integrated, never jumps).
uniform float audioSpread;   ///< Spectral spread, 0..1.
uniform float audioKick;   ///< Kick-drum envelope, 0..1 (fast attack, short decay).
uniform float audioMode;   ///< Mode of the music: 0 minor .. 1 major.
uniform float audioSwell;   ///< Slow loudness envelope, 0..1 (seconds).
uniform float coreP;   ///< Fold core class knob of the 3D chain, 0..1.
uniform float reliefP;   ///< Relief knob, 0..1.
uniform float morphP;   ///< Morph knob: how the scene changes over time, 0..1.
uniform float styleP;   ///< Look knob, 0..1.
uniform float speedP;   ///< Speed knob, 0..1.
uniform float detailP;   ///< Detail knob, 0..1.
uniform float paletteP;   ///< Palette knob: photo colours .. colour field, 0..1.
uniform float camP;   ///< Camera knob, 0..1.
uniform float hueP;   ///< Hue knob (radians), usually the music's chroma hue plus a rolled offset.
/// @brief Pseudo-random number 0..1 from a 2D point.
float hash21(vec2 p)
{
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}
/// @brief Smooth 2D value noise, 0..1.
float noise2(vec2 p)
{
    vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash21(i), hash21(i + vec2(1.0, 0.0)), f.x),
               mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), f.x), f.y);
}
/// @brief Fractal noise of three octaves, 0..1.
float fbm3(vec2 p)
{
    float v = 0.0, a = 0.5;
    for (int i = 0; i < 3; ++i) { v += a * noise2(p); p = mat2(1.6, 1.2, -1.2, 1.6) * p + 2.3; a *= 0.5; }
    return v;
}
/// @brief Mirrored repeat of a coordinate into 0..1 (seamless at every edge).
vec2 mirrorUV(vec2 uv) { return 1.0 - abs(fract(uv * 0.5) * 2.0 - 1.0); }
/// @brief The photo at a mip level, mirrored at its edges: lod 0 full detail, ~4 a soft field, ~7 broad masses.
vec3 imgLod(vec2 uv, float lod) {
    uv = mirrorUV(uv);
    return (interpolation * textureLod(tex0, uv, lod) + (1.0 - interpolation) * textureLod(tex1, uv, lod)).rgb;
}
/// @brief Luminance of a colour (Rec. 601 weights).
float luma(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }
/// @brief HSV (all 0..1) to RGB.
vec3 hsv2rgb(vec3 c) {
    vec3 k = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), k, c.y);
}
/// @brief Saturation of a colour, 0..1.
float satOf(vec3 c) { float mx = max(c.r, max(c.g, c.b)); return (mx - min(c.r, min(c.g, c.b))) / max(mx, 1e-3); }
/// @brief A glowing colour for a place: the photo's own hue where it has one, a wandering hue field where it is grey.
vec3 glowColour(vec3 photo, vec2 q, float hue0) {
    vec3 field = hsv2rgb(vec3(fract(hue0 + 0.55 * fbm3(q * 0.8) + 0.03 * audioAdvance), 0.85, 1.0));
    vec3 own = photo / max(max(photo.r, max(photo.g, photo.b)), 1e-3); own = own * own * own;
    return mix(field, own, smoothstep(0.12, 0.35, satOf(photo)));
}
/// @brief A kaleidoscope of the coordinate around a slowly wandering centre.
vec2 kaleidoUV(vec2 uv, float sides)
{
    vec2 c = vec2(0.5) + 0.2 * vec2(sin(0.0107 * sceneTime), cos(0.0131 * sceneTime));
    vec2 d = uv - c;
    float r = length(d);
    float sec = 6.2831853 / sides;
    float a = abs(mod(atan(d.y, d.x), sec) - 0.5 * sec);
    a += 0.03 * sceneTime + 0.25 * audioPhase;
    return c + r * vec2(cos(a), sin(a));
}
/// @brief The photo through the scene's kaleidoscope.
vec3 imgK(vec2 uv, float lod) { return imgLod(kaleidoUV(uv, 6.0), lod); }
/// @brief The pixel's position, centred and aspect-corrected (y spans -0.5..0.5).
vec2 screenP() { return (gl_FragCoord.xy / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0); }
/// @brief Writes the pixel: loudness brightness and a soft highlight roll-off.
void finish(vec3 col)
{
    col *= 0.9 + 0.2 * audioLevel;
    vec3 t = max(col, 0.0);
    t /= 1.0 + 0.35 * max(t.r, max(t.g, t.b));
    fragColor = vec4(clamp(t, 0.0, 1.0), 1.0);
}
vec3 gCam = vec3(0.0);
uniform float camHost;   ///< 1 when the app drives the camera (camZ, camGaze).
uniform float camZ;   ///< Flight position along the camera path (integrated by the app).
uniform vec3 camGaze;   ///< Gaze shown, gaze panned to, pan progress.
float camFlight(float gt) { return camHost > 0.5 ? camZ : gt; }
float gT, gTC, gSpread, gRot, gMw;
vec2 gCw, gCt;
/// @brief Class position of a knob value (n classes).
int pickStage(float x, int n) { return int(min(floor(clamp(x, 0.0, 1.0) * float(n)), float(n - 1))); }
/// @brief A mirror count 5..9 from a sub-variant.
float sides(float v) { return 5.0 + floor(v * 4.99); }
uniform vec3 walkA, walkB, walkC, walkD, walkS;
uniform float walkHost;   ///< 1 when the app walks this lab's stages (walk uniforms valid).
bool walkAll() { return clamp(morphP, 0.0, 1.0) >= 0.5; }
uniform float glowP;   ///< Glow / afterglow knob, 0..1.
uniform sampler2D texPrevFrame;   ///< The last frame, fully composited (feedback).
vec3 chainAfterglow(vec3 col)
{
    if (glowP <= 0.15) return col;
    vec3 prev = texture(texPrevFrame, gl_FragCoord.xy / resolution).rgb;
    return max(col, prev * (0.78 * smoothstep(0.15, 1.0, glowP)));
}
int ordco(int i) { if (i == 0) return 0; if (i == 1) return 4; if (i == 2) return 8; if (i == 3) return 3; if (i == 4) return 20; if (i == 5) return 15; if (i == 6) return 18; if (i == 7) return 9; if (i == 8) return 6; if (i == 9) return 11; if (i == 10) return 10; if (i == 11) return 16; if (i == 12) return 12; if (i == 13) return 1; if (i == 14) return 19; if (i == 15) return 14; if (i == 16) return 7; if (i == 17) return 13; if (i == 18) return 2; if (i == 19) return 21; if (i == 20) return 5; return 17; }
uniform vec3 walkSpace, walkCore, walkBody;
float sliceZoom(int kc)
{
    if (kc == 5) return 0.35;                                   
    if (kc == 6 || kc == 11 || kc == 12 || kc == 15) return 0.42;   
    if (kc == 17 || kc == 19) return 0.48;                      
    if (kc == 13 || kc == 14 || kc == 20 || kc == 7 || kc == 16) return 0.58;   
    if (kc == 1 || kc == 2 || kc == 21 || kc == 9) return 0.75; 
    if (kc == 10 || kc == 18) return 0.9;                       
    return 1.1;                                                 
}
vec3 sliceAxis(float k, float time)
{
    float i = mod(k, 7.0);
    if (i > 5.5) return normalize(vec3(1.0, 1.0, 1.0));                               
    if (i > 4.5) return normalize(vec3(sin(0.013 * time), cos(0.013 * time), 0.35));  
    if (i > 3.5) return normalize(vec3(0.0, 1.0, 1.0));
    if (i > 2.5) return vec3(1.0, 0.0, 0.0);                                          
    if (i > 1.5) return normalize(vec3(1.0, 1.0, 0.0));
    if (i > 0.5) return normalize(vec3(0.3, 0.2, 1.0));
    return vec3(0.0, 0.0, 1.0);                                                       
}
void sliceFrame(float cam, float time, out vec3 N, out vec3 X, out vec3 Y)
{
    float k0, k1, f;
    if (camHost > 0.5) {
        k0 = camGaze.x; k1 = camGaze.y; f = smoothstep(0.0, 1.0, camGaze.z);
    } else {
        float g = floor(clamp(cam, 0.0, 0.999) * 7.0) + 0.004 * time;
        k0 = floor(g); k1 = k0 + 1.0; f = smoothstep(0.75, 1.0, fract(g));
    }
    N = normalize(mix(sliceAxis(k0, time), sliceAxis(k1, time), f));
    vec3 x0 = normalize(cross(vec3(0.31, 0.83, 0.47), N)), y0 = cross(N, x0);   
    float a = 0.015 * time;                                 
    X = cos(a) * x0 + sin(a) * y0;
    Y = cos(a) * y0 - sin(a) * x0;
}
vec3 chainPlaneC(vec2 c, float lod, float pal)
{
    vec3 ph = imgLod(c, lod);
    vec2 m = mirrorUV(c);
    
    
    float h = hueP * 0.159 + 0.9 * m.x + 0.6 * m.y + 0.25 * luma(ph) + 0.12 * audioPhase + 0.004 * sceneTime + 0.3 * clamp(audioMode, 0.0, 1.0);
    float sat = 0.55 + 0.4 * clamp(audioSwell, 0.0, 1.0);
    vec3 fc = hsv2rgb(vec3(fract(h), sat, 1.0)) * (0.35 + 1.3 * luma(ph)) * (1.0 + 0.4 * clamp(audioKick, 0.0, 1.0));
    return mix(ph, fc, pal);
}

vec3 colour3T(vec3 n, float lod, float pal)
{
    // the three projection planes' chain coordinates, weighted by the normal (tiny weights skipped)
    vec3 w = max(pow(abs(n), vec3(4.0)) - 0.03, 0.0); w /= (w.x + w.y + w.z);
    ivec2 ip = ivec2(gl_FragCoord.xy - chainOff);
    vec3 c = vec3(0.0);
    if (w.x > 0.0) c += chainPlaneC(texelFetch(texChain0, ip, 0).xy, lod, pal) * w.x;
    if (w.y > 0.0) c += chainPlaneC(texelFetch(texChain1, ip, 0).xy, lod, pal) * w.y;
    if (w.z > 0.0) c += chainPlaneC(texelFetch(texChain2, ip, 0).xy, lod, pal) * w.z;
    return c;
}
/// @brief Entry point of this shader stage (the file description says what it draws).
void main()
{

    vec2 p = screenP();
    float kick = clamp(audioKick, 0.0, 1.0);
    float swell = clamp(audioSwell, 0.0, 1.0);
    float mode = clamp(audioMode, 0.0, 1.0);
    gT = (0.15 + 0.25 * clamp(speedP, 0.0, 1.0)) * sceneTime + 1.5 * audioAdvance;
    gRot = 0.02 * sceneTime + 0.2 * audioPhase;
    gSpread = clamp(audioSpread, 0.0, 1.0);
    gTC = (0.03 + 0.06 * clamp(speedP, 0.0, 1.0)) * sceneTime + 0.25 * audioAdvance;
    gMw = 0.012 * sceneTime + 0.15 * sceneAdvance;          
    gCw = vec2(0.5) + 0.15 * vec2(sin(0.017 * sceneTime), cos(0.013 * sceneTime));
    gCt = vec2(0.5) + vec2(0.22 * sin(0.023 * sceneTime + 0.3 * sin(0.011 * sceneTime)), 0.16 * cos(0.019 * sceneTime));
    vec3 ro;
    
    
    
    vec3 sN, sX, sY;
    sliceFrame(camP, sceneTime, sN, sX, sY);
    vec3 sc0 = vec3(0.0, 0.0, 0.25 * camFlight(gT));
    
    vec3 wcore = (walkHost > 0.5 && walkAll()) ? walkCore : vec3(coreP, coreP, 0.0);
    float sView = 3.0 * mix(sliceZoom(ordco(pickStage(wcore.x, 22))), sliceZoom(ordco(pickStage(wcore.y, 22))),
                            smoothstep(0.0, 1.0, wcore.z));
    float sDz = 0.4 * sView;                                
    float sPx = sView / resolution.y;                       
    gCam = sc0 - vec3(0.0, 0.0, 6.0);                       
    vec3 rd = normalize(sN + (sX * p.x + sY * p.y) * 0.25);
    ro = sc0 + (sX * p.x + sY * p.y) * sView - rd;
    vec3 sL = normalize(sX * 0.5 + sY * 0.7 - sN * 0.4);     
    ivec2 ip = ivec2(gl_FragCoord.xy - chainOff);
    vec4 gp = texelFetch(texGPos, ip, 0), gn = texelFetch(texGNrm, ip, 0);
    float t = gp.w; bool hit = t >= 0.0;
    vec3 fp = gp.xyz;
    vec3 lc = mix(vec3(0.7, 0.85, 1.1), vec3(1.15, 0.9, 0.7), mode);
    
    vec3 fogPal = hsv2rgb(vec3(fract(hueP * 0.159 + 0.12 * audioPhase + 0.004 * sceneTime + 0.3 * mode + 0.5), 0.55, 1.0));
    vec3 fogC = mix(glowColour(imgK(vec2(0.5) + 0.2 * p, 5.0), p, hueP * 0.159), fogPal, 0.8 * clamp(paletteP, 0.0, 1.0)) * (0.05 + 0.1 * swell);
    vec3 col = fogC;
    // colour and relief for every pixel: the derivatives must not sit in a pixel branch
    vec3 q = ro + rd * max(t, 0.0);
    vec3 n = normalize(gn.xyz + vec3(1e-6));
    float lod = clamp(log2(max(t, 0.05) * 2.0) + 1.5 * (1.0 - clamp(detailP, 0.0, 1.0)), 0.0, 7.0);
    vec3 nGeo = n;                                          // texture on the geometric normal, light on the bumped one
    vec3 tex0 = colour3T(nGeo, lod, 0.2 + 0.7 * clamp(paletteP, 0.0, 1.0));
    // relief: the colour chain's brightness as height; its slope on the surface from the
    // screen-space derivatives (bump mapping without tangents, Mikkelsen 2010)
    float hgt = luma(tex0);
    vec3 dpx = dFdx(q), dpy = dFdy(q);
    float dhx = dFdx(hgt), dhy = dFdy(hgt);
    if (reliefP > 0.3) {
        vec3 r1 = cross(dpy, n), r2 = cross(n, dpx);
        float det = dot(dpx, r1);
        vec3 sg = (dhx * r1 + dhy * r2) / (abs(det) > 1e-14 ? det : 1e-14);
        sg = sg / max(1.0, length(sg) * 0.1);                    // silhouettes: no spikes
        n = normalize(n - sg * 0.05 * smoothstep(0.3, 1.0, reliefP));
    }
    if (hit) {
        vec3 nGeo = n;                                          
        vec3 tex = tex0;
        float tm = luma(tex);
        tex = max((tex - tm) * 1.5 + tm, 0.0) * 1.5;           
        vec3 L = sL;
        float diff = 0.5 + 0.5 * dot(n, L);   
        float ao = gn.w;
        float fres = pow(1.0 - abs(dot(n, -rd)), 3.0);
        vec3 surf = tex * lc * (0.35 + 0.9 * diff) * ao;
        vec3 rimC = glowColour(tex, fp.xy, hueP * 0.159);
        vec3 rim = rimC * fres * (0.7 + 1.5 * kick) + surf * 0.4;       
        float st = clamp(styleP, 0.0, 1.0);
        vec3 sc = mix(surf + rimC * fres * (0.15 + 0.6 * kick), rim * 1.3 + rimC * 0.12 * ao, smoothstep(0.5, 1.0, st));
        col = mix(fogC, sc, exp(-t * (0.06 + 0.04 * swell)));
    }
    finish(chainAfterglow(col));
    // keeps the walk uniforms: the app finds the lab's stages by their locations
    if (walkHost < -1.0) col += vec3(walkA.x + walkB.x + walkC.x + walkD.x + walkS.x + walkSpace.x + walkCore.x + walkBody.x);
    finish(col);
}
