#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py -- the 3D lab's last pass: colour, relief, light and fog from the G-buffer
// @chain3d
out vec4 fragColor;
uniform sampler2D texGPos, texGNrm;   // the geometry pass
uniform sampler2D texChain0, texChain1, texChain2;   // the colour chain per projection plane
uniform vec2 chainOff;
uniform vec2  resolution;
uniform float time;
uniform sampler2D tex0;
uniform sampler2D tex1;
uniform float interpolation;
uniform float sceneTime;
uniform float sceneAdvance;
uniform float audioAdvance;
uniform float audioLevel;
uniform float audioPhase;
uniform float audioSpread;
uniform float audioKick;
uniform float audioMode;
uniform float audioSwell;
uniform float reliefP;
uniform float styleP;
uniform float speedP;
uniform float detailP;
uniform float paletteP;
uniform float camP;
uniform float hueP;
float hash21(vec2 p)
{
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}
float noise2(vec2 p)
{
    vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash21(i), hash21(i + vec2(1.0, 0.0)), f.x),
               mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), f.x), f.y);
}
float fbm3(vec2 p)
{
    float v = 0.0, a = 0.5;
    for (int i = 0; i < 3; ++i) { v += a * noise2(p); p = mat2(1.6, 1.2, -1.2, 1.6) * p + 2.3; a *= 0.5; }
    return v;
}
vec2 mirrorUV(vec2 uv) { return 1.0 - abs(fract(uv * 0.5) * 2.0 - 1.0); }
vec3 imgLod(vec2 uv, float lod) {
    uv = mirrorUV(uv);
    return (interpolation * textureLod(tex0, uv, lod) + (1.0 - interpolation) * textureLod(tex1, uv, lod)).rgb;
}
float luma(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }
vec3 hsv2rgb(vec3 c) {
    vec3 k = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), k, c.y);
}
float satOf(vec3 c) { float mx = max(c.r, max(c.g, c.b)); return (mx - min(c.r, min(c.g, c.b))) / max(mx, 1e-3); }
vec3 glowColour(vec3 photo, vec2 q, float hue0) {
    vec3 field = hsv2rgb(vec3(fract(hue0 + 0.55 * fbm3(q * 0.8) + 0.03 * audioAdvance), 0.85, 1.0));
    vec3 own = photo / max(max(photo.r, max(photo.g, photo.b)), 1e-3); own = own * own * own;
    return mix(field, own, smoothstep(0.12, 0.35, satOf(photo)));
}
mat2 rot2(float a) { float c = cos(a), s = sin(a); return mat2(c, -s, s, c); }
vec2 kaleidoUV(vec2 uv, float sides)
{
    vec2 c = vec2(0.5) + 0.2 * vec2(sin(0.0107 * sceneTime), cos(0.0131 * sceneTime));
    vec2 d = uv - c;
    float r = length(d);
    float sec = 6.2831853 / sides;
    float a = abs(mod(atan(d.y, d.x), sec) - 0.5 * sec);
    a += 0.03 * sceneTime + 0.25 * audioPhase;
    return c + r * vec2(cos(a), sin(a));
}
vec3 imgK(vec2 uv, float lod) { return imgLod(kaleidoUV(uv, 6.0), lod); }
vec2 screenP() { return (gl_FragCoord.xy / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0); }
void finish(vec3 col)
{
    col *= 0.9 + 0.2 * audioLevel;
    vec3 t = max(col, 0.0);
    t /= 1.0 + 0.35 * max(t.r, max(t.g, t.b));
    fragColor = vec4(clamp(t, 0.0, 1.0), 1.0);
}
vec3 gCam = vec3(0.0);
float gPathAmp = 1.0;
float gTube = 0.45;
float gSide = 0.0;
float gOrtho = 0.0;
vec3 gAxis = vec3(0.0, 0.0, 1.0);
vec2 camPathXY(float z)
{
    return gPathAmp * vec2(1.1 * sin(z * 0.11) + 0.4 * sin(z * 0.23 + 1.3), 0.8 * sin(z * 0.083 + 0.7) + 0.3 * cos(z * 0.19));
}
mat3 camFrame(float z, out vec3 ro)
{
    ro = vec3(camPathXY(z), z);
    vec3 ta = vec3(camPathXY(z + 2.0), z + 2.0);
    vec3 fw = normalize(ta - ro);
    
    
    vec2 curv = camPathXY(z + 1.5) - 2.0 * camPathXY(z) + camPathXY(z - 1.5);
    float roll = clamp(-curv.x * 1.6, -0.3, 0.3);
    vec3 up = vec3(sin(roll), cos(roll), 0.0);
    vec3 rt = normalize(cross(up, fw));
    return mat3(rt, cross(fw, rt), fw);
}
uniform float camHost;
uniform float camZ;
uniform vec3 camGaze;
vec4 gazeAngles(float k, float time)
{
    float i = mod(k, 7.0);
    
    
    if (i > 5.5) return vec4(1.2, 0.3, 1.0, 1.0);
    if (i > 4.5) return vec4(0.035 * time, 0.35 + 0.2 * sin(0.019 * time), 0.0, 1.0);
    if (i > 3.5) return vec4(-0.3, 0.75, 0.0, 0.0);
    if (i > 2.5) return vec4(-1.35, 0.08, 0.0, 1.0);
    if (i > 1.5) return vec4(0.35, -0.8, 0.0, 0.0);
    if (i > 0.5) return vec4(1.35, -0.08, 0.0, 1.0);
    return vec4(0.0);
}
vec3 gazeTurn(vec3 v, vec2 a) { v.yz = rot2(a.y) * v.yz; v.xz = rot2(-a.x) * v.xz; return v; }
float camFlight(float gt) { return camHost > 0.5 ? camZ : gt; }
vec3 gazeDir(vec2 p, float cam, float time, mat3 cf, inout vec3 ro)
{
    float k0, k1, f;
    if (camHost > 0.5) {
        k0 = camGaze.x; k1 = camGaze.y; f = smoothstep(0.0, 1.0, camGaze.z);
    } else {
        float g = floor(clamp(cam, 0.0, 0.999) * 7.0) + 0.004 * time;
        k0 = floor(g); k1 = k0 + 1.0; f = smoothstep(0.75, 1.0, fract(g));
    }
    vec4 a0 = gazeAngles(k0, time), a1 = gazeAngles(k1, time);
    a1.x += 6.2831853 * floor((a0.x - a1.x) / 6.2831853 + 0.5);   
    vec4 a = mix(a0, a1, f);
    a.xy += (1.0 - a.z) * vec2(0.12 * sin(0.031 * time), 0.08 * sin(0.023 * time + 1.0));
    gSide = a.w;
    gOrtho = a.z;
    vec3 ax = gazeTurn(vec3(0.0, 0.0, 1.0), a.xy);
    gAxis = cf * ax;
    ro += cf * gazeTurn(vec3(p, 0.0), a.xy) * (2.2 * gOrtho);
    return cf * normalize(mix(gazeTurn(normalize(vec3(p, 1.1)), a.xy), ax, gOrtho));
}
float gT, gTC, gSpread, gRot, gMw;
vec2 gCw, gCt;
float sides(float v) { return 5.0 + floor(v * 4.99); }
uniform vec3 walkA, walkB, walkC, walkD, walkS;
uniform float walkHost;
uniform vec3 walkSpace, walkCore, walkBody;
vec3 chainPlaneC(vec2 c, float lod, float pal)
{
    vec3 ph = imgLod(c, lod);
    vec2 m = mirrorUV(c);
    
    
    float h = hueP * 0.159 + 0.9 * m.x + 0.6 * m.y + 0.25 * luma(ph) + 0.12 * audioPhase + 0.004 * sceneTime + 0.3 * clamp(audioMode, 0.0, 1.0);
    float sat = 0.55 + 0.4 * clamp(audioSwell, 0.0, 1.0);
    vec3 fc = hsv2rgb(vec3(fract(h), sat, 1.0)) * (0.35 + 1.3 * luma(ph)) * (1.0 + 0.4 * clamp(audioKick, 0.0, 1.0));
    return mix(ph, fc, pal);
}

vec3 colour3T(vec3 n, float lod, float pal)
{
    // the three projection planes' chain coordinates, weighted by the normal (tiny weights skipped)
    vec3 w = max(pow(abs(n), vec3(4.0)) - 0.03, 0.0); w /= (w.x + w.y + w.z);
    ivec2 ip = ivec2(gl_FragCoord.xy - chainOff);
    vec3 c = vec3(0.0);
    if (w.x > 0.0) c += chainPlaneC(texelFetch(texChain0, ip, 0).xy, lod, pal) * w.x;
    if (w.y > 0.0) c += chainPlaneC(texelFetch(texChain1, ip, 0).xy, lod, pal) * w.y;
    if (w.z > 0.0) c += chainPlaneC(texelFetch(texChain2, ip, 0).xy, lod, pal) * w.z;
    return c;
}
void main()
{

    vec2 p = screenP();
    float kick = clamp(audioKick, 0.0, 1.0);
    float swell = clamp(audioSwell, 0.0, 1.0);
    float mode = clamp(audioMode, 0.0, 1.0);
    gT = (0.15 + 0.25 * clamp(speedP, 0.0, 1.0)) * sceneTime + 1.5 * audioAdvance;
    gRot = 0.02 * sceneTime + 0.2 * audioPhase;
    gSpread = clamp(audioSpread, 0.0, 1.0);
    gTC = (0.03 + 0.06 * clamp(speedP, 0.0, 1.0)) * sceneTime + 0.25 * audioAdvance;
    gMw = 0.012 * sceneTime + 0.15 * sceneAdvance;          
    gCw = vec2(0.5) + 0.15 * vec2(sin(0.017 * sceneTime), cos(0.013 * sceneTime));
    gCt = vec2(0.5) + vec2(0.22 * sin(0.023 * sceneTime + 0.3 * sin(0.011 * sceneTime)), 0.16 * cos(0.019 * sceneTime));
    vec3 ro;
    mat3 cf = camFrame(camFlight(gT), ro);
    gCam = ro;
    gTube = 0.4 + 0.15 * swell;                             
    vec3 rd = gazeDir(p, camP, sceneTime, cf, ro);
    ivec2 ip = ivec2(gl_FragCoord.xy - chainOff);
    vec4 gp = texelFetch(texGPos, ip, 0), gn = texelFetch(texGNrm, ip, 0);
    float t = gp.w; bool hit = t >= 0.0;
    vec3 fp = gp.xyz;
    vec3 lc = mix(vec3(0.7, 0.85, 1.1), vec3(1.15, 0.9, 0.7), mode);
    
    vec3 fogPal = hsv2rgb(vec3(fract(hueP * 0.159 + 0.12 * audioPhase + 0.004 * sceneTime + 0.3 * mode + 0.5), 0.55, 1.0));
    vec3 fogC = mix(glowColour(imgK(vec2(0.5) + 0.2 * p, 5.0), p, hueP * 0.159), fogPal, 0.8 * clamp(paletteP, 0.0, 1.0)) * (0.05 + 0.1 * swell);
    vec3 col = fogC;
    // colour and relief for every pixel: the derivatives must not sit in a pixel branch
    vec3 q = ro + rd * max(t, 0.0);
    vec3 n = normalize(gn.xyz + vec3(1e-6));
    float lod = clamp(log2(max(t, 0.05) * 2.0) + 1.5 * (1.0 - clamp(detailP, 0.0, 1.0)), 0.0, 7.0);
    vec3 nGeo = n;                                          // texture on the geometric normal, light on the bumped one
    vec3 tex0 = colour3T(nGeo, lod, 0.2 + 0.7 * clamp(paletteP, 0.0, 1.0));
    // relief: the colour chain's brightness as height; its slope on the surface from the
    // screen-space derivatives (bump mapping without tangents, Mikkelsen 2010)
    float hgt = luma(tex0);
    vec3 dpx = dFdx(q), dpy = dFdy(q);
    float dhx = dFdx(hgt), dhy = dFdy(hgt);
    if (reliefP > 0.3) {
        vec3 r1 = cross(dpy, n), r2 = cross(n, dpx);
        float det = dot(dpx, r1);
        vec3 sg = (dhx * r1 + dhy * r2) / (abs(det) > 1e-14 ? det : 1e-14);
        sg = sg / max(1.0, length(sg) * 0.1);                    // silhouettes: no spikes
        n = normalize(n - sg * 0.05 * smoothstep(0.3, 1.0, reliefP));
    }
    if (hit) {
        vec3 nGeo = n;                                          
        vec3 tex = tex0;
        float tm = luma(tex);
        tex = max((tex - tm) * 1.5 + tm, 0.0) * 1.5;           
        vec3 L = normalize(vec3(0.5, 0.7, -0.4));
        float diff = max(dot(n, L), 0.0);
        float ao = gn.w;
        float fres = pow(1.0 - abs(dot(n, -rd)), 3.0);
        vec3 surf = tex * lc * (0.35 + 0.9 * diff) * ao;
        vec3 rimC = glowColour(tex, fp.xy, hueP * 0.159);
        vec3 rim = rimC * fres * (0.7 + 1.5 * kick) + surf * 0.4;       
        float st = clamp(styleP, 0.0, 1.0);
        vec3 sc = mix(surf + rimC * fres * (0.15 + 0.6 * kick), rim * 1.3 + rimC * 0.12 * ao, smoothstep(0.5, 1.0, st));
        col = mix(fogC, sc, exp(-t * (0.06 + 0.04 * swell)));
    }
    finish(col);
    // keeps the walk uniforms: the app finds the lab's stages by their locations
    if (walkHost < -1.0) col += vec3(walkA.x + walkB.x + walkC.x + walkD.x + walkS.x + walkSpace.x + walkCore.x + walkBody.x);
    finish(col);
}
