#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py -- the 3D lab's geometry pass (G-buffer)
layout(location = 0) out vec4 gbPos;   ///< folded hit point, distance (-1: no hit)
layout(location = 1) out vec4 gbNrm;   ///< normal, ambient occlusion
// world classes: SPEC_SP0/1, SPEC_CO0/1, SPEC_BO0/1 (branch numbers), set by the app
uniform vec2  resolution;   ///< Size of the render target in pixels.
uniform float time;   ///< Seconds since the program started (never reset; see sceneTime).
uniform float sceneTime;   ///< Seconds since this scene was activated.
uniform float sceneAdvance;   ///< The music's advance since this scene was activated (integrated, never jumps).
uniform float audioAdvance;   ///< The music's advance: integrated tempo-weighted energy (never jumps, never runs backwards).
uniform float audioPhase;   ///< Rotation phase driven by the music (integrated, never jumps).
uniform float audioSpread;   ///< Spectral spread, 0..1.
uniform float audioKick;   ///< Kick-drum envelope, 0..1 (fast attack, short decay).
uniform float audioMode;   ///< Mode of the music: 0 minor .. 1 major.
uniform float audioSwell;   ///< Slow loudness envelope, 0..1 (seconds).
uniform float spaceP;   ///< Space class knob of the 3D chain, 0..1.
uniform float coreP;   ///< Fold core class knob of the 3D chain, 0..1.
uniform float bodyP;   ///< Body class knob of the 3D chain, 0..1.
uniform float morphP;   ///< Morph knob: how the scene changes over time, 0..1.
uniform float speedP;   ///< Speed knob, 0..1.
uniform float camP;   ///< Camera knob, 0..1.
/// @brief Pseudo-random number 0..1 from a 2D point.
float hash21(vec2 p)
{
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}
/// @brief Smooth 2D value noise, 0..1.
float noise2(vec2 p)
{
    vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash21(i), hash21(i + vec2(1.0, 0.0)), f.x),
               mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), f.x), f.y);
}
/// @brief 2D rotation matrix.
mat2 rot2(float a) { float c = cos(a), s = sin(a); return mat2(c, -s, s, c); }
/// @brief The pixel's position, centred and aspect-corrected (y spans -0.5..0.5).
vec2 screenP() { return (gl_FragCoord.xy / resolution - 0.5) * vec2(resolution.x / resolution.y, 1.0); }
float gDR = 1.0;
vec3 gP = vec3(0.0);
/// @brief Rotation of p about an axis.
vec3 fRot(vec3 p, vec3 axis, float a)
{
    axis = normalize(axis);
    float c = cos(a), s = sin(a);
    return p * c + cross(axis, p) * s + axis * dot(axis, p) * (1.0 - c);
}
/// @brief Mirror fold in all three axes.
vec3 fAbs(vec3 p) { return abs(p); }
vec3 fOcta(vec3 p)
{
    p = abs(p);
    if (p.x < p.y) p.xy = p.yx;
    if (p.x < p.z) p.xz = p.zx;
    if (p.y < p.z) p.yz = p.zy;
    return p;
}
vec3 fTetra(vec3 p)
{
    if (p.x + p.y < 0.0) p.xy = -p.yx;
    if (p.x + p.z < 0.0) p.xz = -p.zx;
    if (p.y + p.z < 0.0) p.zy = -p.yz;
    return p;
}
vec3 fBox(vec3 p, float l) { return clamp(p, -l, l) * 2.0 - p; }
/// @brief Sphere-inversion fold (Mandelbox style).
vec3 fSphere(vec3 p, float rMin, float rFix)
{
    float r2 = dot(p, p);
    float k = r2 < rMin * rMin ? (rFix * rFix) / (rMin * rMin) : (r2 < rFix * rFix ? (rFix * rFix) / r2 : 1.0);
    gDR *= k;
    return p * k;
}
/// @brief Scale and offset step of a fold (tracks the distance derivative gDR).
vec3 fScale(vec3 p, float s, vec3 offset) { gDR *= abs(s); return p * s - offset; }
vec3 fRepeat(vec3 p, vec3 c) { return c * (abs(mod(p / c - 1.0, 4.0) - 2.0) - 1.0); }
vec3 fPolarZ(vec3 p, float n)
{
    float sec = 6.2831853 / n;
    float a = abs(mod(atan(p.y, p.x), sec) - 0.5 * sec);
    return vec3(length(p.xy) * vec2(cos(a), sin(a)), p.z);
}
vec3 fPoly(vec3 p, float n)
{
    float cospin = cos(3.14159265 / n), scospin = sqrt(max(0.75 - cospin * cospin, 1e-4));
    vec3 nc = vec3(-0.5, -cospin, scospin);
    for (int i = 0; i < 5; ++i) {
        if (float(i) >= n) break;
        p.xy = abs(p.xy);
        p -= 2.0 * min(0.0, dot(p, nc)) * nc;
    }
    return p;
}
vec3 f4DLattice(vec3 p, float c, float a1, float a2, float w)
{
    vec4 q = vec4(p, w);
    q.xw = rot2(a1) * q.xw;
    q.yw = rot2(a2) * q.yw;
    q = c * (abs(mod(q / c - 1.0, 4.0) - 2.0) - 1.0);
    return q.xyz;                                            
}
vec3 fLogSphere(vec3 p, vec3 c, float K, float zoom)
{
    vec3 d = p - c;
    float r = max(length(d), 1e-4), lk = log(K);
    float u = log(r) / lk - zoom;
    float tri = abs(fract(u * 0.5) * 2.0 - 1.0);
    float rn = exp(tri * lk) * 0.6;
    gDR *= rn / r;
    return d / r * rn;
}
vec3 fHyperBall(vec3 p, float k)
{
    vec3 c = vec3(k);
    float R2 = dot(c, c) - 1.0;
    for (int i = 0; i < 7; ++i) {
        p = abs(p);
        if (p.x < p.y) p.xy = p.yx;
        if (p.x < p.z) p.xz = p.zx;
        if (p.y < p.z) p.yz = p.zy;
        vec3 d = p - c;
        float dd = dot(d, d);
        if (dd < R2) { float f = R2 / dd; p = c + d * f; gDR *= f; }
    }
    return p;
}
vec3 fTorusWrap(vec3 p, float R, float cell)
{
    float rho = length(p.xz);
    float arc = atan(p.z, p.x) * R;
    float per = 6.2831853 * R / max(floor(6.2831853 * R / (4.0 * cell) + 0.5), 1.0) / 4.0;   
    gDR *= max(R / max(rho, 0.5), 1.0);
    vec3 q = vec3(rho - R, p.y, arc);
    return per * (abs(mod(q / per - 1.0, 4.0) - 2.0) - 1.0) * vec3(1.0, 1.0, 1.0);
}
vec3 fGyroidWarp(vec3 p, float s, float t)
{
    gDR *= 1.0 + 1.3 * s;
    return p + s * sin(p.yzx * 1.3 + vec3(t, 1.7 * t, 2.3 + t));
}
/// @brief Signed distance bound to an octahedron of size s.
float sdOcta3(vec3 p, float s) { p = abs(p); return (p.x + p.y + p.z - s) * 0.57735027; }
vec3 fHalfSpace(vec3 p, float c)
{
    float h = abs(p.y + 4.0) + 0.35;                          
    gDR *= 1.0 / h;
    return vec3(p.x / h, log(h) * 1.6, p.z / h);
}
vec3 fLogCyl(vec3 p, float K)
{
    float rho = max(length(p.xy), 1e-3), lk = log(K);
    float tri = abs(fract(log(rho) / lk * 0.5) * 2.0 - 1.0);
    float rn = exp(tri * lk) * 0.8;
    gDR *= max(rn / rho, 1e-3);
    return vec3(p.xy / rho * rn, p.z * rn / rho);
}
/// @brief Distance bound to a superquadric (exponent e).
float sdSuperquad(vec3 p, float r, float e)
{
    vec3 a = pow(abs(p) / r, vec3(e));
    return (pow(a.x + a.y + a.z, 1.0 / e) - 1.0) * r * 0.7;
}
/// @brief Distance bound to a Neovius minimal surface sheet.
float sdNeovius(vec3 p, float th) { vec3 c = cos(p); return (abs(3.0 * (c.x + c.y + c.z) + 4.0 * c.x * c.y * c.z) - th) / 9.0; }
/// @brief Distance bound to a Lidinoid minimal surface sheet.
float sdLidinoid(vec3 p, float th)
{
    vec3 s2 = sin(2.0 * p), c = cos(p), s = sin(p), c2 = cos(2.0 * p);
    float f = 0.5 * (s2.x * c.y * s.z + s2.y * c.z * s.x + s2.z * c.x * s.y) - 0.5 * (c2.x * c2.y + c2.y * c2.z + c2.z * c2.x) + 0.15;
    return (abs(f) - th) / 3.0;
}
/// @brief The world rolled round the z axis.
vec3 fRollZ(vec3 p, float R, float cell)
{
    float rho = length(p.xy), arc = atan(p.y, p.x) * R;
    float per = 6.2831853 * R / max(floor(6.2831853 * R / (4.0 * cell) + 0.5), 1.0) / 4.0;
    gDR *= max(R / max(rho, 0.5), 1.0);
    vec3 q = vec3(rho - R, arc, p.z);
    return per * (abs(mod(q / per - 1.0, 4.0) - 2.0) - 1.0);
}
/// @brief Signed distance bound to a tetrahedron of size s.
float sdTetra3(vec3 p, float s) { return (max(abs(p.x + p.y) - p.z, abs(p.x - p.y) + p.z) - s) * 0.57735027; }
/// @brief Signed distance bound to an icosahedron of size s.
float sdIcosa3(vec3 p, float s)
{
    p = abs(p);
    const float g = 1.618034, ig = 0.618034;
    float d = dot(p, vec3(1.0));
    d = max(d, dot(p, vec3(0.0, ig, g)));
    d = max(d, dot(p, vec3(ig, g, 0.0)));
    d = max(d, dot(p, vec3(g, 0.0, ig)));
    return (d * 0.57735027 - s);
}
vec3 fTwistZ(vec3 p, float k) { vec2 q = rot2(k * p.z) * p.xy; return vec3(q, p.z); }
vec3 fInvert(vec3 p, float R) { float r2 = max(dot(p, p), 1e-4); gDR *= R * R / r2; return p * R * R / r2; }
vec3 fWarp(vec3 p, float s, float t)
{
    
    
    
    gDR *= 1.0 + 1.3 * s;
    return p + s * (vec3(noise2(p.yz * 0.8 + t), noise2(p.zx * 0.8 + 3.1 - t), noise2(p.xy * 0.8 + 5.7 + t)) - 0.5) * 1.6;
}
float sdSphere3(vec3 p, float r) { return length(p) - r; }
/// @brief Signed distance to a box of half size b.
float sdBox3(vec3 p, vec3 b) { vec3 q = abs(p) - b; return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0); }
/// @brief Signed distance to a torus (ring radius R, tube radius r).
float sdTorus3(vec3 p, float R, float r) { return length(vec2(length(p.xz) - R, p.y)) - r; }
/// @brief Distance bound to a gyroid sheet of the given thickness.
float sdGyroid3(vec3 p, float thick) { return (abs(dot(sin(p), cos(p.yzx))) - thick) / 1.8; }
float field3(vec3 p);
vec3 gCam = vec3(0.0);
float gPathAmp = 1.0;
float gTube = 0.45;
float gSide = 0.0;
float gOrtho = 0.0;
vec3 gAxis = vec3(0.0, 0.0, 1.0);
/// @brief The camera path's x/y offset at depth z.
vec2 camPathXY(float z)
{
    return gPathAmp * vec2(1.1 * sin(z * 0.11) + 0.4 * sin(z * 0.23 + 1.3), 0.8 * sin(z * 0.083 + 0.7) + 0.3 * cos(z * 0.19));
}
/// @brief Smooth maximum of two distances (blend width k).
float smaxK(float a, float b, float k) { float h = clamp(0.5 - 0.5 * (b - a) / k, 0.0, 1.0); return mix(b, a, h) + k * h * (1.0 - h); }
/// @brief The world's distance field with the flight tube carved out.
float fieldD(vec3 p)
{
    gDR = 1.0;
    float d = field3(p);
    float tube = max(gTube - length(p.xy - camPathXY(p.z)), -1.0);
    
    
    
    
    if (gSide > 0.0) tube = mix(tube, -1.0, gSide * smoothstep(3.0, 6.0, abs(p.z - gCam.z)));
    
    
    
    if (gOrtho > 0.0) tube = max(tube, mix(-1.0, 0.35 - abs(dot(p - gCam, gAxis)), gOrtho));
    return max(smaxK(d, 0.8 * tube, 0.15), 0.3 - length(p - gCam));
}
mat3 camFrame(float z, out vec3 ro)
{
    ro = vec3(camPathXY(z), z);
    vec3 ta = vec3(camPathXY(z + 2.0), z + 2.0);
    vec3 fw = normalize(ta - ro);
    
    
    vec2 curv = camPathXY(z + 1.5) - 2.0 * camPathXY(z) + camPathXY(z - 1.5);
    float roll = clamp(-curv.x * 1.6, -0.3, 0.3);
    vec3 up = vec3(sin(roll), cos(roll), 0.0);
    vec3 rt = normalize(cross(up, fw));
    return mat3(rt, cross(fw, rt), fw);
}
uniform float camHost;   ///< 1 when the app drives the camera (camZ, camGaze).
uniform float camZ;   ///< Flight position along the camera path (integrated by the app).
uniform vec3 camGaze;   ///< Gaze shown, gaze panned to, pan progress.
vec4 gazeAngles(float k, float time)
{
    float i = mod(k, 7.0);
    
    
    if (i > 5.5) return vec4(1.2, 0.3, 1.0, 1.0);
    if (i > 4.5) return vec4(0.035 * time, 0.35 + 0.2 * sin(0.019 * time), 0.0, 1.0);
    if (i > 3.5) return vec4(-0.3, 0.75, 0.0, 0.0);
    if (i > 2.5) return vec4(-1.35, 0.08, 0.0, 1.0);
    if (i > 1.5) return vec4(0.35, -0.8, 0.0, 0.0);
    if (i > 0.5) return vec4(1.35, -0.08, 0.0, 1.0);
    return vec4(0.0);
}
/// @brief Turns a direction by the gaze angles (yaw, pitch).
vec3 gazeTurn(vec3 v, vec2 a) { v.yz = rot2(a.y) * v.yz; v.xz = rot2(-a.x) * v.xz; return v; }
float camFlight(float gt) { return camHost > 0.5 ? camZ : gt; }
vec3 gazeDir(vec2 p, float cam, float time, mat3 cf, inout vec3 ro)
{
    float k0, k1, f;
    if (camHost > 0.5) {
        k0 = camGaze.x; k1 = camGaze.y; f = smoothstep(0.0, 1.0, camGaze.z);
    } else {
        float g = floor(clamp(cam, 0.0, 0.999) * 7.0) + 0.004 * time;
        k0 = floor(g); k1 = k0 + 1.0; f = smoothstep(0.75, 1.0, fract(g));
    }
    vec4 a0 = gazeAngles(k0, time), a1 = gazeAngles(k1, time);
    a1.x += 6.2831853 * floor((a0.x - a1.x) / 6.2831853 + 0.5);   
    vec4 a = mix(a0, a1, f);
    a.xy += (1.0 - a.z) * vec2(0.12 * sin(0.031 * time), 0.08 * sin(0.023 * time + 1.0));
    gSide = a.w;
    gOrtho = a.z;
    vec3 ax = gazeTurn(vec3(0.0, 0.0, 1.0), a.xy);
    gAxis = cf * ax;
    ro += cf * gazeTurn(vec3(p, 0.0), a.xy) * (2.2 * gOrtho);
    return cf * normalize(mix(gazeTurn(normalize(vec3(p, 1.1)), a.xy), ax, gOrtho));
}
float gT, gTC, gSpread, gRot, gMw;
vec2 gCw, gCt;
/// @brief Class position of a knob value (n classes).
int pickStage(float x, int n) { return int(min(floor(clamp(x, 0.0, 1.0) * float(n)), float(n - 1))); }
/// @brief Sub-variant of a knob value within its class, 0..1.
float subVar(float x, int n) { return fract(clamp(x, 0.0, 0.9999) * float(n)); }
uniform float walkHost;   ///< 1 when the app walks this lab's stages (walk uniforms valid).
bool walkAll() { return clamp(morphP, 0.0, 1.0) >= 0.5; }
vec3 zRepeat(vec3 q, float c) { q.z = c * (abs(mod(q.z / c - 1.0, 4.0) - 2.0) - 1.0); return q; }
vec3 fHexXY(vec3 p, float cell)
{
    vec2 q = p.xy / cell;
    const vec2 s = vec2(1.0, 1.7320508);
    vec2 a = mod(q, s) - s * 0.5, b = mod(q - s * 0.5, s) - s * 0.5;
    vec2 h = dot(a, a) < dot(b, b) ? a : b;
    float an = abs(mod(atan(h.y, h.x), 1.0471976) - 0.5235988);
    return vec3(length(h) * vec2(cos(an), sin(an)) * cell, p.z);
}
int ordsp(int i) { if (i == 0) return 0; if (i == 1) return 9; if (i == 2) return 17; if (i == 3) return 15; if (i == 4) return 14; if (i == 5) return 1; if (i == 6) return 18; if (i == 7) return 7; if (i == 8) return 16; if (i == 9) return 11; if (i == 10) return 3; if (i == 11) return 4; if (i == 12) return 10; if (i == 13) return 12; if (i == 14) return 19; if (i == 15) return 6; if (i == 16) return 2; if (i == 17) return 13; if (i == 18) return 5; return 8; }
int ordco(int i) { if (i == 0) return 0; if (i == 1) return 2; if (i == 2) return 14; if (i == 3) return 21; if (i == 4) return 8; if (i == 5) return 16; if (i == 6) return 1; if (i == 7) return 7; if (i == 8) return 4; if (i == 9) return 13; if (i == 10) return 18; if (i == 11) return 3; if (i == 12) return 15; if (i == 13) return 11; if (i == 14) return 5; if (i == 15) return 12; if (i == 16) return 17; if (i == 17) return 10; if (i == 18) return 20; if (i == 19) return 9; if (i == 20) return 19; return 6; }
int ordbo(int i) { if (i == 0) return 21; if (i == 1) return 20; if (i == 2) return 16; if (i == 3) return 15; if (i == 4) return 1; if (i == 5) return 11; if (i == 6) return 9; if (i == 7) return 7; if (i == 8) return 0; if (i == 9) return 12; if (i == 10) return 19; if (i == 11) return 18; if (i == 12) return 10; if (i == 13) return 17; if (i == 14) return 5; if (i == 15) return 14; if (i == 16) return 6; if (i == 17) return 2; if (i == 18) return 13; if (i == 19) return 4; if (i == 20) return 3; return 8; }
uniform vec3 walkSpace, walkCore, walkBody;
float fieldK_0(vec3 p, float xs, float xc, float xb, int world)
{
    gDR = 1.0;
    int ks = ordsp(pickStage(xs, 20)); float vs = subVar(xs, 20);
    int kc = ordco(pickStage(xc, 22)); float vc = subVar(xc, 22);
    int kb = ordbo(pickStage(xb, 22)); float vb = subVar(xb, 22);
    
    ks = SPEC_SP0; kc = SPEC_CO0; kb = SPEC_BO0;
    vec3 q;
    
#if SPEC_SP0 == 0
    q = fRepeat(p, vec3(1.2 + 0.4 * vs));
#elif SPEC_SP0 == 1
    { q = fPolarZ(p, 6.0 + 2.0 * floor(vs * 2.99)); q.x -= 2.2; q = zRepeat(q, 0.8); }
#elif SPEC_SP0 == 2
    q = fRepeat(fTwistZ(p, 0.25 * sin(gT * 0.05)), vec3(1.4));
#elif SPEC_SP0 == 3
    q = fOcta(fRepeat(p, vec3(1.5)));
#elif SPEC_SP0 == 4
    q = fRepeat(fRot(p, vec3(0.0, 0.0, 1.0), 0.3 * sin(gRot)), vec3(1.2, 1.2, 1.8));
#elif SPEC_SP0 == 5
    {                                     
        q = fPolarZ(fTwistZ(p, 0.3 + 0.2 * vs), 5.0 + 2.0 * floor(vs * 2.99)); q.x -= 2.0; q = zRepeat(q, 0.7);
    }
#elif SPEC_SP0 == 6
    q = zRepeat(fHexXY(p, 2.2 + 0.6 * vs), 1.2);
#elif SPEC_SP0 == 8
    {                                     
        q = fRepeat(p, vec3(1.7 + 0.3 * vs)); q = fInvert(q + vec3(0.3, 0.2, 0.0), 1.4);   
        q = fRepeat(fScale(q, 1.6, vec3(0.0)), vec3(1.3));                                   
    }
#elif SPEC_SP0 == 9
    q = fRepeat(fScale(fLogSphere(p, gCam + vec3(0.0, 0.0, 6.0), 2.5 + vs, gT * 0.05), 2.5, vec3(0.0)), vec3(1.4));
#elif SPEC_SP0 == 12
    q = fRepeat(fHalfSpace(p, 1.0), vec3(1.3));
#elif SPEC_SP0 == 13
    { q = fPolarZ(fTwistZ(p, 0.6 + 0.3 * vs), 2.0); q.x -= 1.4; q = zRepeat(q, 0.6); }
#elif SPEC_SP0 == 14
    q = fRepeat(fLogCyl(p, 2.5 + vs), vec3(1.2));
#elif SPEC_SP0 == 15
    q = fPoly(fRepeat(p, vec3(1.6)), 5.0);
#elif SPEC_SP0 == 16
    { q = fRepeat(p, vec3(1.5)); float kb2 = 0.35 + 0.25 * vs; q.xy = rot2(kb2 * q.x) * q.xy; gDR *= 1.0 + 1.5 * kb2; }
#elif SPEC_SP0 == 17
    { vec3 cc = gCam + vec3(0.0, 0.0, 6.0); float lr = log(max(length(p - cc), 1e-3));
        q = fLogSphere(p, cc, 2.5 + vs, gT * 0.05); q.xy = rot2(0.9 * lr) * q.xy; gDR *= 1.9; q = fRepeat(fScale(q, 2.5, vec3(0.0)), vec3(1.4)); }
#elif SPEC_SP0 == 18
    { float ws = 0.3 + 0.2 * vs; q = fRepeat(fWarp(p, ws, gT * 0.05), vec3(1.4)); }
#elif SPEC_SP0 == 19
    q = fRollZ(p, 3.2 + vs, 1.2);
#elif SPEC_SP0 == 10
    q = fTorusWrap(p, 7.0 + 3.0 * vs, 1.3);
#elif SPEC_SP0 == 11
    q = fRepeat(fGyroidWarp(p, 0.25 + 0.15 * vs, gT * 0.05), vec3(1.4));
#elif SPEC_SP0 == 7
    q = f4DLattice(p, 1.3 + 0.3 * vs, 0.35 * sin(gT * 0.04) + gRot * 0.3, 0.25 * sin(gT * 0.031 + 1.0), 0.6 * sin(gT * 0.023));
#endif
   
    float bs = 1.0;                                         
    
#if SPEC_CO0 == 1
    {
        for (int i = 0; i < 3; ++i) { q = fTetra(q); q = fRot(q, vec3(1.0, 1.0, 0.0), gRot * 0.5 + 0.3 * vc); q = fScale(q, 1.7, vec3(0.45)); }
        bs = 1.4;
    }
#elif SPEC_CO0 == 2
    {
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fRot(q, vec3(0.0, 1.0, 1.0), gRot * 0.5 + 0.4 * vc); q = fScale(q, 1.6, vec3(0.6, 0.3, 0.2)); }
        bs = 1.4;
    }
#elif SPEC_CO0 == 3
    {
        q = fSphere(q, 0.45 + 0.1 * vc, 1.0); q = fBox(q, 0.6); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.5);
        bs = 1.0;
    }
#elif SPEC_CO0 == 4
    {
        q = fAbs(q); q = fRot(q, vec3(0.0, 0.0, 1.0), 0.4 * sin(gRot) + vc); q = fAbs(q) - vec3(0.25 + 0.1 * vc); q = fRot(q, vec3(1.0, 0.0, 0.0), 0.3 * sin(gT * 0.07));
        bs = 0.8;
    }
#elif SPEC_CO0 == 5
    {
        
        
        for (int i = 0; i < 3; ++i) {
            q = fOcta(q);
            q = fRot(q, vec3(1.0, 1.0, 1.0), 0.12 * sin(gRot) + 0.15 * vc);
            q = fScale(q, 3.0, vec3(2.0));
            if (q.z < -1.0) q.z += 2.0;
        }
        bs = 2.6;
    }
#elif SPEC_CO0 == 6
    {
        
        
        q = fScale(q, 1.8, vec3(0.0));                      
        for (int i = 0; i < 4; ++i) {
            q = 2.0 * clamp(q, -vec3(0.8, 0.8, 1.0), vec3(0.8, 0.8, 1.0)) - q;
            float k = max((1.05 + 0.3 * vc) / max(dot(q, q), 1e-4), 1.0);
            q *= k; gDR *= k;
        }
        bs = 0.7;
    }
#elif SPEC_CO0 == 7
    {
        
        for (int i = 0; i < 3; ++i) { q = fPoly(q, 5.0); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.4 + 0.3 * vc); q = fScale(q, 1.9, vec3(0.55, 0.3, 0.9)); }
        bs = 1.2;
    }
#elif SPEC_CO0 == 8
    {
        
        
        q = fPoly(q, 3.0 + floor(vc * 2.99)); q.z -= 0.35;
        bs = 0.7;
    }
#elif SPEC_CO0 == 9
    {
        
        q = fHyperBall(q * 0.8, 0.85 + 0.1 * vc) / 0.8;
        bs = 0.45;
    }
#elif SPEC_CO0 == 10
    {
        
        
        for (int i = 0; i < 3; ++i) {
            q.xy = clamp(q.xy, -1.0, 1.0) * 2.0 - q.xy;
            float r2 = max(dot(q, q), 1e-4);
            float k = r2 < 0.25 ? 4.0 : (r2 < 1.0 ? 1.0 / r2 : 1.0);
            q *= k; gDR *= k;
            q = fRot(q, vec3(0.0, 0.0, 1.0), 0.3 + 0.4 * vc + 0.2 * sin(gRot));
            q = fScale(q, 1.25, vec3(0.0));
        }
        bs = 3.0;   
    }
#elif SPEC_CO0 == 11
    {                                    
        const vec3 CS = vec3(0.92436, 0.90756, 0.92436);
        for (int i = 0; i < 5; ++i) {
            q = 2.0 * clamp(q, -CS, CS) - q;
            float k = max((1.0 + 0.15 * vc) / max(dot(q, q), 1e-4), 1.0);
            q *= k; gDR *= k;
        }
        bs = 0.6;
    }
#elif SPEC_CO0 == 12
    {                                  
        for (int i = 0; i < 4; ++i) {
            float r2 = max(dot(q, q), 0.08);
            q = abs(q) / r2 - vec3(0.5 + 0.3 * vc, 0.4, 0.6); gDR /= r2;
        }
        bs = 0.9;
    }
#elif SPEC_CO0 == 13
    {                                  
        for (int i = 0; i < 3; ++i) { q = fPoly(q, 5.0); q = fRot(q, vec3(0.0, 0.0, 1.0), gRot * 0.3 + 0.2 * vc); q = fScale(q, 2.0, vec3(0.0, 0.53, 0.85)); }
        bs = 1.2;
    }
#elif SPEC_CO0 == 14
    {                                  
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.3 + 0.2 * vc); q = fScale(q, 2.0, vec3(1.0, 0.0, 0.0)); }
        bs = 1.8;
    }
#elif SPEC_CO0 == 15
    {                                  
        for (int i = 0; i < 3; ++i) {
            q = abs(fract(q * 0.25 + 0.25) * 4.0 - 2.0) - 1.0;   
            float k = (1.1 + 0.2 * vc) / max(dot(q, q), 1e-3);
            q *= k; gDR *= k;
        }
        bs = 1.6;
    }
#elif SPEC_CO0 == 16
    {                                    
        vec3 z = q * 1.3, c0 = z; float dr = 1.0, r = length(z);
        for (int i = 0; i < 3; ++i) {
            r = length(z); if (r > 2.0) break;
            float th0 = acos(clamp(z.z / max(r, 1e-4), -1.0, 1.0)) * 8.0 + gRot * 0.3, ph0 = atan(z.y, z.x) * 8.0;
            dr = pow(r, 7.0) * 8.0 * dr + 1.0;
            z = pow(r, 8.0) * vec3(sin(th0) * cos(ph0), sin(th0) * sin(ph0), cos(th0)) + c0;
        }
        r = length(z);
        gP = c0;
        return 0.5 * log(max(r, 1e-4)) * r / dr / 1.3 / gDR * 0.8;
    }
#elif SPEC_CO0 == 17
    {                                  
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fScale(q, 2.4, vec3(1.4, 1.4, 0.0)); if (q.z < -0.7) q.z += 1.4; }
        bs = 2.2;
    }
#elif SPEC_CO0 == 18
    {                                  
        for (int i = 0; i < 2; ++i) { q = fOcta(q); q = fBox(q, 0.8); q = fSphere(q, 0.4, 1.0); q = fScale(q, 1.6, vec3(0.4, 0.2, 0.1) * (1.0 + vc)); }
        bs = 2.4;   
    }
#elif SPEC_CO0 == 19
    {                                  
        for (int i = 0; i < 4; ++i) { if (i == 1 || i == 3) q = fOcta(q); else q = fTetra(q); q = fScale(q, 1.8, vec3(0.8 + 0.3 * vc)); }
        bs = 1.6;
    }
#elif SPEC_CO0 == 20
    {                                  
        for (int i = 0; i < 3; ++i) { q = abs(q); q = fSphere(q, 0.4, 0.9); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.3 + 0.3 * vc); q = fScale(q, 2.0, vec3(0.9)); }
        bs = 1.3;
    }
#elif SPEC_CO0 == 21
    {                                  
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fRot(q, vec3(0.2, 1.0, 0.5), gRot * 0.4 + 0.35 * float(i + 1) + vc); q = fScale(q, 1.6, vec3(0.45, 0.22, 0.08)); }
        bs = 2.6;   
    }
#endif

    gP = q;
    float th = 1.0 + 0.3 * gSpread;
    float d;
    
#if SPEC_BO0 == 0
    d = sdBox3(q, vec3(0.35 + 0.1 * vb, 0.3, 0.35) * bs * th);
#elif SPEC_BO0 == 1
    d = sdSphere3(q, 0.45 * bs * th);
#elif SPEC_BO0 == 2
    d = sdTorus3(q.xzy, 0.5 * bs, 0.12 * bs * th);
#elif SPEC_BO0 == 3
    d = sdGyroid3(q * (3.0 / bs), 0.25 + 0.2 * gSpread) * bs / 3.0;
#elif SPEC_BO0 == 5
    { vec3 w = q * (3.0 / bs); d = (abs(cos(w.x) + cos(w.y) + cos(w.z)) - 0.35 - 0.3 * gSpread) / 2.2 * bs / 3.0; }
#elif SPEC_BO0 == 6
    { vec3 w = q * (3.0 / bs); vec3 sn = sin(w), cs = cos(w);                     
        d = (abs(sn.x * sn.y * sn.z + sn.x * cs.y * cs.z + cs.x * sn.y * cs.z + cs.x * cs.y * sn.z) - 0.25 - 0.2 * gSpread) / 2.2 * bs / 3.0; }
#elif SPEC_BO0 == 7
    d = sdOcta3(q, 0.6 * bs * th);
#elif SPEC_BO0 == 9
    d = sdSuperquad(q, 0.5 * bs * th, 2.5 + 6.0 * vb);
#elif SPEC_BO0 == 10
    d = max(abs(length(q) - 0.5 * bs * th) - 0.05 * bs, -sdOcta3(q, 0.75 * bs));
#elif SPEC_BO0 == 11
    { vec3 w = q; w.x -= clamp(w.x, -0.25 * bs, 0.25 * bs); d = sdTorus3(w.xzy, 0.3 * bs, 0.07 * bs * th); }
#elif SPEC_BO0 == 12
    d = sdNeovius(q * (3.0 / bs), 0.4 + 0.8 * gSpread) * bs / 3.0;
#elif SPEC_BO0 == 13
    d = sdLidinoid(q * (3.0 / bs), 0.05 + 0.05 * gSpread) * bs / 3.0;
#elif SPEC_BO0 == 8
    d = min(min(length(q.xy), length(q.yz)), length(q.zx)) - 0.1 * bs * th;
#elif SPEC_BO0 == 14
    d = min(sdTetra3(q, 0.4 * bs * th), sdTetra3(-q, 0.4 * bs * th));
#elif SPEC_BO0 == 15
    d = max(max(length(q.xy), length(q.yz)), length(q.zx)) - 0.4 * bs * th;
#elif SPEC_BO0 == 16
    { vec3 w = q; w.xz = rot2(q.y * 2.5) * w.xz; d = sdBox3(w, vec3(0.16, 0.6, 0.16) * bs * th) * 0.6; }
#elif SPEC_BO0 == 17
    d = (max(max(abs(q.x) + abs(q.y), abs(q.y) + abs(q.z)), abs(q.z) + abs(q.x)) - 0.6 * bs * th) * 0.7071;
#elif SPEC_BO0 == 18
    d = sdIcosa3(q, 0.45 * bs * th);
#elif SPEC_BO0 == 19
    { float R = 0.38 * bs, r0 = 0.07 * bs * th; vec3 a = q + vec3(0.2 * bs, 0.0, 0.0), b = q - vec3(0.2 * bs, 0.0, 0.0);
        d = min(length(vec2(length(a.xy) - R, a.z)) - r0, length(vec2(length(b.xz) - R, b.y)) - r0); }
#elif SPEC_BO0 == 20
    { float rho = length(q.xy), Rr = 0.45 * bs + 0.06 * bs * smoothstep(-0.3, 0.3, sin(12.0 * atan(q.y, q.x)));
        d = max(max(rho - Rr, 0.2 * bs - rho), abs(q.z) - 0.08 * bs * th) * 0.7; }
#elif SPEC_BO0 == 21
    { vec3 w = q; w.x -= clamp(w.x, -0.3 * bs, 0.3 * bs); d = length(w) - 0.15 * bs * th; }
#else
    d = min(min(sdBox3(q, vec3(0.6, 0.08, 0.08) * bs * th), sdBox3(q, vec3(0.08, 0.6, 0.08) * bs * th)), sdBox3(q, vec3(0.08, 0.08, 0.6) * bs * th));
#endif

    return d / gDR * 0.8;
}
float fieldK_1(vec3 p, float xs, float xc, float xb, int world)
{
    gDR = 1.0;
    int ks = ordsp(pickStage(xs, 20)); float vs = subVar(xs, 20);
    int kc = ordco(pickStage(xc, 22)); float vc = subVar(xc, 22);
    int kb = ordbo(pickStage(xb, 22)); float vb = subVar(xb, 22);
    
    ks = SPEC_SP1; kc = SPEC_CO1; kb = SPEC_BO1;
    vec3 q;
    
#if SPEC_SP1 == 0
    q = fRepeat(p, vec3(1.2 + 0.4 * vs));
#elif SPEC_SP1 == 1
    { q = fPolarZ(p, 6.0 + 2.0 * floor(vs * 2.99)); q.x -= 2.2; q = zRepeat(q, 0.8); }
#elif SPEC_SP1 == 2
    q = fRepeat(fTwistZ(p, 0.25 * sin(gT * 0.05)), vec3(1.4));
#elif SPEC_SP1 == 3
    q = fOcta(fRepeat(p, vec3(1.5)));
#elif SPEC_SP1 == 4
    q = fRepeat(fRot(p, vec3(0.0, 0.0, 1.0), 0.3 * sin(gRot)), vec3(1.2, 1.2, 1.8));
#elif SPEC_SP1 == 5
    {                                     
        q = fPolarZ(fTwistZ(p, 0.3 + 0.2 * vs), 5.0 + 2.0 * floor(vs * 2.99)); q.x -= 2.0; q = zRepeat(q, 0.7);
    }
#elif SPEC_SP1 == 6
    q = zRepeat(fHexXY(p, 2.2 + 0.6 * vs), 1.2);
#elif SPEC_SP1 == 8
    {                                     
        q = fRepeat(p, vec3(1.7 + 0.3 * vs)); q = fInvert(q + vec3(0.3, 0.2, 0.0), 1.4);   
        q = fRepeat(fScale(q, 1.6, vec3(0.0)), vec3(1.3));                                   
    }
#elif SPEC_SP1 == 9
    q = fRepeat(fScale(fLogSphere(p, gCam + vec3(0.0, 0.0, 6.0), 2.5 + vs, gT * 0.05), 2.5, vec3(0.0)), vec3(1.4));
#elif SPEC_SP1 == 12
    q = fRepeat(fHalfSpace(p, 1.0), vec3(1.3));
#elif SPEC_SP1 == 13
    { q = fPolarZ(fTwistZ(p, 0.6 + 0.3 * vs), 2.0); q.x -= 1.4; q = zRepeat(q, 0.6); }
#elif SPEC_SP1 == 14
    q = fRepeat(fLogCyl(p, 2.5 + vs), vec3(1.2));
#elif SPEC_SP1 == 15
    q = fPoly(fRepeat(p, vec3(1.6)), 5.0);
#elif SPEC_SP1 == 16
    { q = fRepeat(p, vec3(1.5)); float kb2 = 0.35 + 0.25 * vs; q.xy = rot2(kb2 * q.x) * q.xy; gDR *= 1.0 + 1.5 * kb2; }
#elif SPEC_SP1 == 17
    { vec3 cc = gCam + vec3(0.0, 0.0, 6.0); float lr = log(max(length(p - cc), 1e-3));
        q = fLogSphere(p, cc, 2.5 + vs, gT * 0.05); q.xy = rot2(0.9 * lr) * q.xy; gDR *= 1.9; q = fRepeat(fScale(q, 2.5, vec3(0.0)), vec3(1.4)); }
#elif SPEC_SP1 == 18
    { float ws = 0.3 + 0.2 * vs; q = fRepeat(fWarp(p, ws, gT * 0.05), vec3(1.4)); }
#elif SPEC_SP1 == 19
    q = fRollZ(p, 3.2 + vs, 1.2);
#elif SPEC_SP1 == 10
    q = fTorusWrap(p, 7.0 + 3.0 * vs, 1.3);
#elif SPEC_SP1 == 11
    q = fRepeat(fGyroidWarp(p, 0.25 + 0.15 * vs, gT * 0.05), vec3(1.4));
#elif SPEC_SP1 == 7
    q = f4DLattice(p, 1.3 + 0.3 * vs, 0.35 * sin(gT * 0.04) + gRot * 0.3, 0.25 * sin(gT * 0.031 + 1.0), 0.6 * sin(gT * 0.023));
#endif
   
    float bs = 1.0;                                         
    
#if SPEC_CO1 == 1
    {
        for (int i = 0; i < 3; ++i) { q = fTetra(q); q = fRot(q, vec3(1.0, 1.0, 0.0), gRot * 0.5 + 0.3 * vc); q = fScale(q, 1.7, vec3(0.45)); }
        bs = 1.4;
    }
#elif SPEC_CO1 == 2
    {
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fRot(q, vec3(0.0, 1.0, 1.0), gRot * 0.5 + 0.4 * vc); q = fScale(q, 1.6, vec3(0.6, 0.3, 0.2)); }
        bs = 1.4;
    }
#elif SPEC_CO1 == 3
    {
        q = fSphere(q, 0.45 + 0.1 * vc, 1.0); q = fBox(q, 0.6); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.5);
        bs = 1.0;
    }
#elif SPEC_CO1 == 4
    {
        q = fAbs(q); q = fRot(q, vec3(0.0, 0.0, 1.0), 0.4 * sin(gRot) + vc); q = fAbs(q) - vec3(0.25 + 0.1 * vc); q = fRot(q, vec3(1.0, 0.0, 0.0), 0.3 * sin(gT * 0.07));
        bs = 0.8;
    }
#elif SPEC_CO1 == 5
    {
        
        
        for (int i = 0; i < 3; ++i) {
            q = fOcta(q);
            q = fRot(q, vec3(1.0, 1.0, 1.0), 0.12 * sin(gRot) + 0.15 * vc);
            q = fScale(q, 3.0, vec3(2.0));
            if (q.z < -1.0) q.z += 2.0;
        }
        bs = 2.6;
    }
#elif SPEC_CO1 == 6
    {
        
        
        q = fScale(q, 1.8, vec3(0.0));                      
        for (int i = 0; i < 4; ++i) {
            q = 2.0 * clamp(q, -vec3(0.8, 0.8, 1.0), vec3(0.8, 0.8, 1.0)) - q;
            float k = max((1.05 + 0.3 * vc) / max(dot(q, q), 1e-4), 1.0);
            q *= k; gDR *= k;
        }
        bs = 0.7;
    }
#elif SPEC_CO1 == 7
    {
        
        for (int i = 0; i < 3; ++i) { q = fPoly(q, 5.0); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.4 + 0.3 * vc); q = fScale(q, 1.9, vec3(0.55, 0.3, 0.9)); }
        bs = 1.2;
    }
#elif SPEC_CO1 == 8
    {
        
        
        q = fPoly(q, 3.0 + floor(vc * 2.99)); q.z -= 0.35;
        bs = 0.7;
    }
#elif SPEC_CO1 == 9
    {
        
        q = fHyperBall(q * 0.8, 0.85 + 0.1 * vc) / 0.8;
        bs = 0.45;
    }
#elif SPEC_CO1 == 10
    {
        
        
        for (int i = 0; i < 3; ++i) {
            q.xy = clamp(q.xy, -1.0, 1.0) * 2.0 - q.xy;
            float r2 = max(dot(q, q), 1e-4);
            float k = r2 < 0.25 ? 4.0 : (r2 < 1.0 ? 1.0 / r2 : 1.0);
            q *= k; gDR *= k;
            q = fRot(q, vec3(0.0, 0.0, 1.0), 0.3 + 0.4 * vc + 0.2 * sin(gRot));
            q = fScale(q, 1.25, vec3(0.0));
        }
        bs = 3.0;   
    }
#elif SPEC_CO1 == 11
    {                                    
        const vec3 CS = vec3(0.92436, 0.90756, 0.92436);
        for (int i = 0; i < 5; ++i) {
            q = 2.0 * clamp(q, -CS, CS) - q;
            float k = max((1.0 + 0.15 * vc) / max(dot(q, q), 1e-4), 1.0);
            q *= k; gDR *= k;
        }
        bs = 0.6;
    }
#elif SPEC_CO1 == 12
    {                                  
        for (int i = 0; i < 4; ++i) {
            float r2 = max(dot(q, q), 0.08);
            q = abs(q) / r2 - vec3(0.5 + 0.3 * vc, 0.4, 0.6); gDR /= r2;
        }
        bs = 0.9;
    }
#elif SPEC_CO1 == 13
    {                                  
        for (int i = 0; i < 3; ++i) { q = fPoly(q, 5.0); q = fRot(q, vec3(0.0, 0.0, 1.0), gRot * 0.3 + 0.2 * vc); q = fScale(q, 2.0, vec3(0.0, 0.53, 0.85)); }
        bs = 1.2;
    }
#elif SPEC_CO1 == 14
    {                                  
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.3 + 0.2 * vc); q = fScale(q, 2.0, vec3(1.0, 0.0, 0.0)); }
        bs = 1.8;
    }
#elif SPEC_CO1 == 15
    {                                  
        for (int i = 0; i < 3; ++i) {
            q = abs(fract(q * 0.25 + 0.25) * 4.0 - 2.0) - 1.0;   
            float k = (1.1 + 0.2 * vc) / max(dot(q, q), 1e-3);
            q *= k; gDR *= k;
        }
        bs = 1.6;
    }
#elif SPEC_CO1 == 16
    {                                    
        vec3 z = q * 1.3, c0 = z; float dr = 1.0, r = length(z);
        for (int i = 0; i < 3; ++i) {
            r = length(z); if (r > 2.0) break;
            float th0 = acos(clamp(z.z / max(r, 1e-4), -1.0, 1.0)) * 8.0 + gRot * 0.3, ph0 = atan(z.y, z.x) * 8.0;
            dr = pow(r, 7.0) * 8.0 * dr + 1.0;
            z = pow(r, 8.0) * vec3(sin(th0) * cos(ph0), sin(th0) * sin(ph0), cos(th0)) + c0;
        }
        r = length(z);
        gP = c0;
        return 0.5 * log(max(r, 1e-4)) * r / dr / 1.3 / gDR * 0.8;
    }
#elif SPEC_CO1 == 17
    {                                  
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fScale(q, 2.4, vec3(1.4, 1.4, 0.0)); if (q.z < -0.7) q.z += 1.4; }
        bs = 2.2;
    }
#elif SPEC_CO1 == 18
    {                                  
        for (int i = 0; i < 2; ++i) { q = fOcta(q); q = fBox(q, 0.8); q = fSphere(q, 0.4, 1.0); q = fScale(q, 1.6, vec3(0.4, 0.2, 0.1) * (1.0 + vc)); }
        bs = 2.4;   
    }
#elif SPEC_CO1 == 19
    {                                  
        for (int i = 0; i < 4; ++i) { if (i == 1 || i == 3) q = fOcta(q); else q = fTetra(q); q = fScale(q, 1.8, vec3(0.8 + 0.3 * vc)); }
        bs = 1.6;
    }
#elif SPEC_CO1 == 20
    {                                  
        for (int i = 0; i < 3; ++i) { q = abs(q); q = fSphere(q, 0.4, 0.9); q = fRot(q, vec3(1.0, 1.0, 1.0), gRot * 0.3 + 0.3 * vc); q = fScale(q, 2.0, vec3(0.9)); }
        bs = 1.3;
    }
#elif SPEC_CO1 == 21
    {                                  
        for (int i = 0; i < 3; ++i) { q = fOcta(q); q = fRot(q, vec3(0.2, 1.0, 0.5), gRot * 0.4 + 0.35 * float(i + 1) + vc); q = fScale(q, 1.6, vec3(0.45, 0.22, 0.08)); }
        bs = 2.6;   
    }
#endif

    gP = q;
    float th = 1.0 + 0.3 * gSpread;
    float d;
    
#if SPEC_BO1 == 0
    d = sdBox3(q, vec3(0.35 + 0.1 * vb, 0.3, 0.35) * bs * th);
#elif SPEC_BO1 == 1
    d = sdSphere3(q, 0.45 * bs * th);
#elif SPEC_BO1 == 2
    d = sdTorus3(q.xzy, 0.5 * bs, 0.12 * bs * th);
#elif SPEC_BO1 == 3
    d = sdGyroid3(q * (3.0 / bs), 0.25 + 0.2 * gSpread) * bs / 3.0;
#elif SPEC_BO1 == 5
    { vec3 w = q * (3.0 / bs); d = (abs(cos(w.x) + cos(w.y) + cos(w.z)) - 0.35 - 0.3 * gSpread) / 2.2 * bs / 3.0; }
#elif SPEC_BO1 == 6
    { vec3 w = q * (3.0 / bs); vec3 sn = sin(w), cs = cos(w);                     
        d = (abs(sn.x * sn.y * sn.z + sn.x * cs.y * cs.z + cs.x * sn.y * cs.z + cs.x * cs.y * sn.z) - 0.25 - 0.2 * gSpread) / 2.2 * bs / 3.0; }
#elif SPEC_BO1 == 7
    d = sdOcta3(q, 0.6 * bs * th);
#elif SPEC_BO1 == 9
    d = sdSuperquad(q, 0.5 * bs * th, 2.5 + 6.0 * vb);
#elif SPEC_BO1 == 10
    d = max(abs(length(q) - 0.5 * bs * th) - 0.05 * bs, -sdOcta3(q, 0.75 * bs));
#elif SPEC_BO1 == 11
    { vec3 w = q; w.x -= clamp(w.x, -0.25 * bs, 0.25 * bs); d = sdTorus3(w.xzy, 0.3 * bs, 0.07 * bs * th); }
#elif SPEC_BO1 == 12
    d = sdNeovius(q * (3.0 / bs), 0.4 + 0.8 * gSpread) * bs / 3.0;
#elif SPEC_BO1 == 13
    d = sdLidinoid(q * (3.0 / bs), 0.05 + 0.05 * gSpread) * bs / 3.0;
#elif SPEC_BO1 == 8
    d = min(min(length(q.xy), length(q.yz)), length(q.zx)) - 0.1 * bs * th;
#elif SPEC_BO1 == 14
    d = min(sdTetra3(q, 0.4 * bs * th), sdTetra3(-q, 0.4 * bs * th));
#elif SPEC_BO1 == 15
    d = max(max(length(q.xy), length(q.yz)), length(q.zx)) - 0.4 * bs * th;
#elif SPEC_BO1 == 16
    { vec3 w = q; w.xz = rot2(q.y * 2.5) * w.xz; d = sdBox3(w, vec3(0.16, 0.6, 0.16) * bs * th) * 0.6; }
#elif SPEC_BO1 == 17
    d = (max(max(abs(q.x) + abs(q.y), abs(q.y) + abs(q.z)), abs(q.z) + abs(q.x)) - 0.6 * bs * th) * 0.7071;
#elif SPEC_BO1 == 18
    d = sdIcosa3(q, 0.45 * bs * th);
#elif SPEC_BO1 == 19
    { float R = 0.38 * bs, r0 = 0.07 * bs * th; vec3 a = q + vec3(0.2 * bs, 0.0, 0.0), b = q - vec3(0.2 * bs, 0.0, 0.0);
        d = min(length(vec2(length(a.xy) - R, a.z)) - r0, length(vec2(length(b.xz) - R, b.y)) - r0); }
#elif SPEC_BO1 == 20
    { float rho = length(q.xy), Rr = 0.45 * bs + 0.06 * bs * smoothstep(-0.3, 0.3, sin(12.0 * atan(q.y, q.x)));
        d = max(max(rho - Rr, 0.2 * bs - rho), abs(q.z) - 0.08 * bs * th) * 0.7; }
#elif SPEC_BO1 == 21
    { vec3 w = q; w.x -= clamp(w.x, -0.3 * bs, 0.3 * bs); d = length(w) - 0.15 * bs * th; }
#else
    d = min(min(sdBox3(q, vec3(0.6, 0.08, 0.08) * bs * th), sdBox3(q, vec3(0.08, 0.6, 0.08) * bs * th)), sdBox3(q, vec3(0.08, 0.08, 0.6) * bs * th));
#endif

    return d / gDR * 0.8;
}
float field3(vec3 p)
{
    float xs = spaceP, xc = coreP, xb = bodyP, ys = xs, yc = xc, yb = xb, f = 0.0;
    if (walkHost > 0.5 && walkAll()) {
        xs = walkSpace.x; xc = walkCore.x; xb = walkBody.x;
        ys = walkSpace.y; yc = walkCore.y; yb = walkBody.y;
        f = smoothstep(0.0, 1.0, max(walkSpace.z, max(walkCore.z, walkBody.z)));   
    }
    float d0 = fieldK_0(p, xs, xc, xb, 0);
#if SPEC_SP0 == SPEC_SP1 && SPEC_CO0 == SPEC_CO1 && SPEC_BO0 == SPEC_BO1
    return d0;
#else
    if (f <= 0.0) return d0;
    vec3 p0 = gP;
    float d1 = fieldK_1(p, ys, yc, yb, 1);
    gP = mix(p0, gP, f);
    return mix(d0, d1, f);
#endif
}
/// @brief Entry point of this shader stage (the file description says what it draws).
void main()
{

    vec2 p = screenP();
    float kick = clamp(audioKick, 0.0, 1.0);
    float swell = clamp(audioSwell, 0.0, 1.0);
    float mode = clamp(audioMode, 0.0, 1.0);
    gT = (0.15 + 0.25 * clamp(speedP, 0.0, 1.0)) * sceneTime + 1.5 * audioAdvance;
    gRot = 0.02 * sceneTime + 0.2 * audioPhase;
    gSpread = clamp(audioSpread, 0.0, 1.0);
    gTC = (0.03 + 0.06 * clamp(speedP, 0.0, 1.0)) * sceneTime + 0.25 * audioAdvance;
    gMw = 0.012 * sceneTime + 0.15 * sceneAdvance;          
    gCw = vec2(0.5) + 0.15 * vec2(sin(0.017 * sceneTime), cos(0.013 * sceneTime));
    gCt = vec2(0.5) + vec2(0.22 * sin(0.023 * sceneTime + 0.3 * sin(0.011 * sceneTime)), 0.16 * cos(0.019 * sceneTime));
    vec3 ro;
    mat3 cf = camFrame(camFlight(gT), ro);
    gCam = ro;
    gTube = 0.4 + 0.15 * swell;                             
    vec3 rd = gazeDir(p, camP, sceneTime, cf, ro);
    int z0 = min(int(sceneTime), 0);       // a start the compiler cannot see: the loop stays a loop
    float t = 0.05; bool hit = false; vec3 fp = vec3(0.0);
    vec3 q = vec3(0.0), n = vec3(0.0), e = vec3(0.0);
    float ao = 0.0;
    int stage = 0;                         // 0 march, 1..4 normal taps (tetrahedron), 5..6 AO taps
    for (int i = z0; i < 107; ++i) {
        vec3 pos = ro + rd * t;
        if (stage > 4) pos = q + n * (0.06 * float(stage - 4));
        else if (stage > 0) {
            int k = stage - 1;
            e = 0.5773 * (2.0 * vec3(float(((k + 3) >> 1) & 1), float((k >> 1) & 1), float(k & 1)) - 1.0);
            pos = q + 0.0015 * e;
        }
        float d = fieldD(pos);
        if (stage == 0) {
            if (abs(d) < 0.0015 * t) { hit = true; fp = gP; q = pos; stage = 1; continue; }
            t += d * 0.8;
            if (t > 30.0 || i >= 99) break;
        } else if (stage <= 4) {
            n += e * d;
            if (stage == 4) n = normalize(n);
            ++stage;
        } else {
            float h = 0.06 * float(stage - 4);
            ao += (h - d) / h;
            if (stage == 6) break;
            ++stage;
        }
    }
    if (!hit) { gbPos = vec4(0.0, 0.0, 0.0, -1.0); gbNrm = vec4(0.0, 0.0, 1.0, 1.0); return; }
    gbPos = vec4(fp, t);
    gbNrm = vec4(n, clamp(1.0 - 0.4 * ao, 0.2, 1.0));
}
