#version 330 core
// GENERATED by Tools/scenegen/make_chainpass.py -- the 3D lab: one plane's chain input
out vec4 fragColor;
uniform sampler2D texGPos;
uniform int plane;
uniform float solidP;
void main()
{
    vec4 g = texelFetch(texGPos, ivec2(gl_FragCoord.xy), 0);
    vec3 fp = g.xyz;
    float sd = solidP >= 0.5 ? 1.0 : 0.0;
    vec2 uv = plane == 0 ? fp.yz : (plane == 1 ? fp.zx : fp.xy);
    float depth = plane == 0 ? fp.x : (plane == 1 ? fp.y : fp.z);
    fragColor = vec4(uv * 0.35 + 0.5, depth * sd, 0.0);
}
