#version 330 core
out vec4 fragColor;
/**
 * @file SolitonInternalWaveAndamanSea.frag
 * @brief SOLITON INTERNAL WAVE ANDAMAN SEA: Giant oceanic internal gravity wave soliton packets
 * generated by tidal flow over submarine sills. Massive subsurface pycnocline depressions create
 * distinctive surface wave roughness strips, refractive sun glitter bands, and ocean photo texturing.
 *   audioAdvance -> propels internal wave packet propagation across Andaman pycnocline
 *   audioKick    -> flashes surface wave breaking foam & turbulent boil bursts
 *   audioSwell   -> deepens internal pycnocline depression amplitude & wave crest width
 *   audioCentroid-> shifts tropical ocean water transmission color spectra
 *   audioMid     -> modulates capillary wave roughness within soliton convergence zones
 *
 * Per-activation variety:
 *   packetCountP float number of ranked internal soliton waves (3.0..8.0)
 *   pycnoclineP  float subsurface thermocline depth scale      (0.6..2.2)
 *   glitterP     float surface sun glitter reflectivity gain   (0.8..2.5)
 *   roughnessP   float capillary wave roughness intensity      (0.5..2.0)
 */

uniform vec2  resolution;
uniform float time;
uniform sampler2D tex0;
uniform sampler2D tex1;
uniform float interpolation;

uniform float audioPhase;
uniform float audioAdvance;
uniform float audioSwell;
uniform float audioLevel;
uniform float audioKick;
uniform float audioCentroid;
uniform float audioValence;
uniform float audioChromaHue;
uniform float audioSubBass;
uniform float audioBass;
uniform float audioMid;
uniform float audioHigh;
uniform float audioFlux;

uniform float packetCountP;
uniform float pycnoclineP;
uniform float glitterP;
uniform float roughnessP;

vec3 img(vec2 uv) {
    return (interpolation * texture(tex0, uv) + (1.0 - interpolation) * texture(tex1, uv)).rgb;
}

vec3 imgPalette(float t)
{
    float ang = audioChromaHue + audioAdvance * 0.04 + t * 6.2831853;
    float rad = 0.16 + 0.08 * sin(audioAdvance * 0.013);
    vec3  col = img(clamp(vec2(0.5) + rad * vec2(cos(ang), sin(ang)), 0.0, 1.0));
    float g   = dot(col, vec3(0.333));
    return mix(vec3(g), col, 0.55 + 0.45 * audioValence);
}

vec3 palTint(vec3 c, float t, float k)
{
    vec3 tp = imgPalette(t);
    tp *= dot(c, vec3(0.3333)) / max(dot(tp, vec3(0.3333)), 1e-3);
    return mix(c, tp, k);
}

void main()
{
    vec2 uv = (gl_FragCoord.xy - 0.5 * resolution) / min(resolution.x, resolution.y);
    float t = time * 0.35 + audioAdvance * 0.3;
    
    // Internal wave packet propagating diagonally (Korteweg-de Vries ranked soliton train)
    vec2 waveDir = normalize(vec2(0.7, 0.7));
    float waveDist = dot(uv, waveDir) * 6.0 - t * 2.5;
    
    float numSolitons = (packetCountP > 1.0 ? packetCountP : 5.0);
    float internalDepression = 0.0;
    
    // KdV soliton train: sum of sech^2((x - c_i*t) / Delta_i) with decreasing amplitudes
    for (float i = 0.0; i < 6.0; i += 1.0) {
        if (i >= numSolitons) break;
        
        float solitonSpacing = i * 1.6;
        float amp = 1.0 / (1.0 + i * 0.45);
        float width = 0.8 + i * 0.2;
        
        float localX = (waveDist - solitonSpacing) / width;
        float sech = 1.0 / cosh(localX * 2.0);
        internalDepression += (sech * sech) * amp;
    }
    
    internalDepression *= (pycnoclineP > 0.01 ? pycnoclineP : 1.2) * (0.8 + 0.4 * audioSwell);
    
    // Surface roughness / slicks above internal solitons
    float rScale = (roughnessP > 0.01 ? roughnessP : 1.0);
    float capillary = sin(uv.x * 35.0 + uv.y * 25.0 - t * 6.0) * cos(uv.y * 30.0 + t * 4.0);
    float surfaceRoughness = capillary * internalDepression * rScale * (0.6 + 0.8 * audioMid);
    
    // Sun glitter band on convergence front
    float glitter = pow(clamp(internalDepression * 1.2 + surfaceRoughness * 0.4, 0.0, 1.0), 3.0);
    glitter *= (1.0 + 3.0 * audioKick) * (glitterP > 0.01 ? glitterP : 1.3);
    
    // Andaman Sea deep cyan / turquoise water colors
    vec3 deepWater  = vec3(0.04, 0.25, 0.45);
    vec3 oceanGlaze = vec3(0.15, 0.85, 0.95);
    vec3 foamWhite  = vec3(0.9, 0.95, 1.0);
    
    vec3 waterCol = palTint(mix(deepWater, oceanGlaze, clamp(internalDepression * 0.5, 0.0, 1.0)), uv.y * 0.2 + audioCentroid, 0.26);
    
    // Background photo sampling
    vec2 bgUv = gl_FragCoord.xy / resolution;
    vec3 bg = img(bgUv) * 0.25;
    
    vec3 col = bg + waterCol * 0.8;
    col += waterCol * internalDepression * 1.5;
    col += foamWhite * glitter * 2.2;
    col += palTint(vec3(0.8, 1.0, 0.9), t * 0.05, 0.2) * abs(surfaceRoughness) * 0.9;
    col += waterCol * (audioKick * 0.35);
    
    // Soft knee compression
    col /= 1.0 + 0.35 * max(col.r, max(col.g, col.b));
    fragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
