# -*- coding: utf-8 -*-
"""Regression test of the chain runner: every chain class, passes against the uber shader, pixel for pixel.

The app runs the chain labs as one small pass per transform (Engine/ChainPass,
generated by Tools/scenegen/make_chainpass.py); the editor and KALEIDO_NO_CHAINPASS
run the lab's own uber shader.  Both must give the same picture.  With
KALEIDO_FREEZE_TIME (the scene stands at one moment, silent audio),
KALEIDO_FIXED_PHOTO and KALEIDO_SEED two runs are pixel-identical, so any
difference is a bug in the generator or the runner.

Run i pins stage A to class i, B to class i mod 23, C to i mod 18, D to i mod 20
(the 2D lab's positions), so every class of every stage is shown at least once
in 58 runs; the order, the time tilt and the look vary with i too.  Each run is
a full-resolution screenshot of the app (web remote /api/screenshot), once with
the runner and once without.  The repo ini is backed up and restored.

  python Tools/chain_regress.py                 # all 58 combinations (~1 h)
  python Tools/chain_regress.py --every 6       # every 6th (~10 min)
  python Tools/chain_regress.py --only 12 30    # these combinations
Exit code: the number of combinations whose mean difference exceeds --tol.
"""
import argparse, io, os, re, shutil, subprocess, sys, time, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REL = os.path.join(ROOT, "Release")
# KALEIDO_EXE: a copy of the app in Release/ (a long run goes on while the app is rebuilt)
EXE = os.environ.get("KALEIDO_EXE", "Kaleidoscope.exe")
INI = os.path.join(ROOT, "kaleidoscope_settings.ini")
sys.path.insert(0, os.path.join(ROOT, "Tools", "scenegen"))
import chain_classes as cc                                    # noqa: E402

N = {"chainAP": 58, "chainBP": 23, "chainCP": 18, "chainDP": 20}


def preset(pins):
    src = io.open(os.path.join(ROOT, "Presets", "Komplett.xml"), encoding="utf-8").read()
    fx = re.search(r"[ \t]*<CombineShader\b[^>]*[\\/]FxPlain\.frag\"[^>]*>.*?</CombineShader>", src, re.S).group(0)
    blk = re.search(r"[ \t]*<TextureShader\b[^>]*[\\/]ChainLab2D\.frag\"[^>]*>.*?</TextureShader>", src, re.S).group(0)
    for k, v in pins.items():
        blk = re.sub(r'(<float name="%s") minValue="[^"]*" maxValue="[^"]*"' % k, r'\1 minValue="%s" maxValue="%s"' % (v, v), blk)
    head, rest = blk.split(">", 1)
    head = re.sub(r'\s(probability|minTimeSolo|maxTimeSolo)="[^"]*"', "", head)
    blk = head + ' probability="1.0" minTimeSolo="100" maxTimeSolo="120">' + rest
    return ('<?xml version="1.0" encoding="utf-8" ?>\n<configuration ImageDirectory="..' + "\\\\" + 'Images" '
            'ConfigurationName="_regress" hidden="true">\n' + blk + "\n" + fx + "\n</configuration>\n")


def shot(pins, out, runner, photo, wait):
    io.open(os.path.join(ROOT, "Presets", "_regress.xml"), "w", encoding="utf-8").write(preset(pins))
    env = dict(os.environ, KALEIDO_MAX_RUNTIME_SECS=str(int(wait) + 10), KALEIDO_NO_ACTIVATE="1",
               KALEIDO_FREEZE_TIME="30", KALEIDO_FIXED_PHOTO=photo, KALEIDO_SEED="7",
               KALEIDO_CHAIN_SS="0")   # supersampling changes the sparkling classes on purpose
    if not runner:
        env["KALEIDO_NO_CHAINPASS"] = "1"
    p = subprocess.Popen([os.path.join(REL, EXE), "-c", "_regress", "-l"], cwd=REL, env=env,
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        for attempt in range(4):                              # the uber shader may still be compiling
            time.sleep(wait if attempt == 0 else 3)
            lg = io.open(os.path.join(REL, "kaleidoscope.log"), encoding="utf-8", errors="replace").read()
            m = re.search(r"WEB REMOTE: http://<this-pc>:(\d+)/", lg)
            try:
                urllib.request.urlopen("http://127.0.0.1:%s/api/screenshot" % (m.group(1) if m else "8091"), timeout=5).read()
            except OSError:
                continue
            time.sleep(1.5)
            lg = io.open(os.path.join(REL, "kaleidoscope.log"), encoding="utf-8", errors="replace").read()
            saved = re.findall(r"Saved screenshot: (.*)", lg)
            if saved:
                f = saved[-1].strip()
                shutil.move(f if os.path.isabs(f) else os.path.join(REL, f), out)
                return True
        return False
    finally:
        p.wait(timeout=60)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--every", type=int, default=1, help="only every n-th combination")
    ap.add_argument("--only", type=int, nargs="*", help="these combinations (0..57)")
    ap.add_argument("--tol", type=float, default=0.5, help="mean absolute difference (0..255) that counts as a failure")
    ap.add_argument("--photo", default=None, help="the fixed photo (default: the first in Images/)")
    ap.add_argument("--wait", type=float, default=22.0,
                    help="seconds before the screenshot (the exposure settles on the frozen frame: ~20 s)")
    ap.add_argument("--keep", help="keep the screenshots in this folder")
    a = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")
    from PIL import Image
    import numpy as np
    photo = a.photo or sorted(os.listdir(os.path.join(ROOT, "Images")))[0]
    work = a.keep or os.path.join(os.environ.get("TEMP", "."), "chain_regress")
    os.makedirs(work, exist_ok=True)
    combos = a.only if a.only else list(range(0, 58, a.every))
    backup = INI + ".regress_backup"
    shutil.copy(INI, backup)
    fails = 0
    try:
        for i in combos:
            pins = {k: "%.4f" % ((i % n + 0.5) / n) for k, n in N.items()}
            pins.update({"morphP": "0", "orderP": "%.4f" % ((i * 7 % 24 + 0.5) / 24), "tiltP": "%.2f" % (0.3 + 0.7 * (i % 3) / 2),
                         "styleP": "%.4f" % ((i % 5 + 0.5) / 5), "glowP": "0", "speedP": "0.5", "detailP": "0.6", "paletteP": "0.4"})
            names = " | ".join(cc.CLASSES[k][i % n] or "none" for k, n in N.items())
            ra, rb = os.path.join(work, "run_%02d.png" % i), os.path.join(work, "uber_%02d.png" % i)
            if not (shot(pins, ra, True, photo, a.wait) and shot(pins, rb, False, photo, a.wait + 2)):
                print("%2d  NO SCREENSHOT  %s" % (i, names), flush=True)
                fails += 1
                continue
            x = np.asarray(Image.open(ra).convert("RGB")).astype(float)
            y = np.asarray(Image.open(rb).convert("RGB")).astype(float)
            d = abs(x - y).mean()
            bad = d > a.tol
            fails += bad
            print("%2d  %s  diff %.3f  %s" % (i, "FAIL" if bad else "ok  ", d, names), flush=True)
    finally:
        shutil.copy(backup, INI)
        os.remove(backup)
        try:
            os.remove(os.path.join(ROOT, "Presets", "_regress.xml"))
        except OSError:
            pass
    print("%d of %d combinations differ" % (fails, len(combos)))
    sys.exit(min(fails, 255))


if __name__ == "__main__":
    main()
