# -*- coding: utf-8 -*-
"""Regenerate the genre presets (and the one Test preset) from Komplett.xml.

Komplett.xml is the master list: every scene and FX entry lives there with
its mood tags, formulas and parameter ranges.  This tool filters that master
by mood into the genre configurations, so adding a scene to Komplett (with
moods) and re-running this script is all it takes to roll it out everywhere.

    python Tools/make_genre_configs.py          (run from the repo root)

Genres (scene AND FX entries are filtered by the same rule):
    Ambient      calm or dreamy, never aggressive
    Club         aggressive, or bright without calm
    Noir         dark
    Psychedelic  psychedelic
    Galerie      calm/bright/dreamy, never aggressive or psychedelic
    Allround     everything
    TestAlle     everything, hidden — the name starts with "Test", which
                 flips the engine into review mode (alphabetical order,
                 fixed 8 s per scene, 'n' steps onward)
"""
import re, os, sys

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

SRC = "Configurations/Komplett.xml"
IMAGE_DIR = "C:\\\\Users\\\\rene\\\\Desktop\\\\BilderPhotoechoes"

def rule_ambient(m):     return ("calm" in m or "dreamy" in m) and "aggressive" not in m
def rule_club(m):        return "aggressive" in m or ("bright" in m and "calm" not in m)
def rule_noir(m):        return "dark" in m
def rule_psychedelic(m): return "psychedelic" in m
def rule_galerie(m):     return (("calm" in m or "bright" in m or "dreamy" in m)
                                 and "aggressive" not in m and "psychedelic" not in m)
def rule_all(m):         return True

GENRES = [
    ("Ambient",     rule_ambient,     False),
    ("Club",        rule_club,        False),
    ("Noir",        rule_noir,        False),
    ("Psychedelic", rule_psychedelic, False),
    ("Galerie",     rule_galerie,     False),
    ("Allround",    rule_all,         False),
    ("TestAlle",    rule_all,         True),
]

src = open(SRC, encoding="utf-8").read()

# Whole entry blocks (open tag .. matching close tag), scenes and FX alike.
BLOCK = re.compile(
    r"[ \t]*<(TextureShader|CombineShader)\b[^>]*>.*?</\1>[ \t]*\n",
    re.S)
blocks = []
for m in BLOCK.finditer(src):
    tag = m.group(1)
    head = m.group(0).split(">", 1)[0]
    mm = re.search(r'mood="([^"]*)"', head)
    moods = set(t.strip() for t in mm.group(1).split(",")) if mm else set()
    fm = re.search(r'file="[^"]*[\\/](\w+)\.(?:frag)"', head)
    name = fm.group(1) if fm else "?"
    blocks.append((tag, name, moods, m.group(0)))

scenes = [b for b in blocks if b[0] == "TextureShader"]
fx     = [b for b in blocks if b[0] == "CombineShader"]
print("master: %d scenes, %d fx" % (len(scenes), len(fx)))

for name, rule, hidden in GENRES:
    sel_s = [b for b in scenes if rule(b[2])]
    sel_f = [b for b in fx if rule(b[2])]
    hid = ' hidden="true"' if hidden else ""
    out = ['<?xml version="1.0" encoding="utf-8" ?>',
           '<configuration ImageDirectory="%s" ConfigurationName="%s"%s >'
           % (IMAGE_DIR, name, hid),
           "",
           "  <!-- GENERATED by Tools/make_genre_configs.py from Komplett.xml -->",
           "  <!-- %d scenes + %d FX overlays, filtered by mood tags -->" % (len(sel_s), len(sel_f)),
           ""]
    for b in sel_s + sel_f:
        out.append(b[3].rstrip("\n"))
    out.append("")
    out.append("</configuration>")
    out.append("")
    path = "Configurations/%s.xml" % name
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("%-12s %3d scenes  %2d fx -> %s" % (name, len(sel_s), len(sel_f), path))
