#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate an inspection preset: every scene, 5 s each, no overlay FX.

    python Tools/make_test_preset.py [-o Configurations/TestPlain.xml]

Komplett.xml exists to play well -- probabilities differ, moods gate which
scenes a track may pick, overlays and transitions are part of the show. That is
exactly wrong for looking AT the shaders: a scene can sit unseen for an hour,
and when it does appear an overlay is painting over it.

This preset is the opposite. Every scene, equal probability, a fixed 5 s solo,
and FxPlain as the only combine so nothing is layered on top. Pair it with the
runtime marking keys (SPACE marks, SHIFT+SPACE writes Configurations/Marked.xml)
to walk the catalogue and shortlist whatever looks wrong.

SCENES RUN IN ALPHABETICAL ORDER, not at random. That is not configured here:
Configuration.cpp turns on the scheduler's review mode for any preset whose
ConfigurationName starts with "Test", and review mode steps m_reviewOrder,
which is the scene list sorted by fragment filename across Scene2D and Scene3D
alike. The name below therefore MUST keep its "Test" prefix -- rename it and
the walk silently goes back to random, which for an inspection pass means
never knowing whether you have seen everything.

Review mode also caps a scene at 8 s; 5 s is below that, so it applies as
written.

Each scene's REAL node is copied out of Komplett.xml, so geom kind and preset
parameters come along. Synthesising tags instead would drop both and show a
broken render of a working shader -- that mistake has already cost this project
a full measurement campaign.

Two caveats worth knowing while inspecting:
  * The 5 s is divided by the audio-driven timingScale, so with energetic music
    playing scenes turn over faster and with ambient material slower. For an
    even walk, inspect in silence or with steady material.
  * Mood tags still ride along on the copied nodes. They bias selection when
    music is playing; in silence every scene is eligible.
"""
import os
import re
import sys
import xml.dom.minidom as minidom

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.join(ROOT, "Configurations", "Komplett.xml")

SOLO_SECONDS = 5
FADE_SECONDS = 1


def main():
    out_path = os.path.join(ROOT, "Configurations", "TestPlain.xml")
    if "-o" in sys.argv:
        out_path = sys.argv[sys.argv.index("-o") + 1]
        if not os.path.isabs(out_path):
            out_path = os.path.join(ROOT, out_path)

    try:
        doc = minidom.parse(MASTER)
    except Exception as e:
        print("cannot parse %s: %s" % (MASTER, e))
        return 1

    root = doc.documentElement
    scenes = [el for el in root.getElementsByTagName("TextureShader")]
    if not scenes:
        print("no <TextureShader> entries in %s" % MASTER)
        return 1

    out = minidom.Document()
    cfg = out.createElement("configuration")
    cfg.setAttribute("ImageDirectory", root.getAttribute("ImageDirectory"))
    cfg.setAttribute("ConfigurationName", "TestPlain")
    cfg.setAttribute("hidden", "true")      # a bench, not something to land on by accident
    out.appendChild(cfg)
    cfg.appendChild(out.createComment(
        " GENERATED by Tools/make_test_preset.py, do not hand-edit. "
        "Every scene, %d s each, alphabetical order, FxPlain only. "
        "The alphabetical walk comes from the Test* name prefix (review mode); "
        "renaming this preset silently makes it random again. "
        "Mark scenes with SPACE while it runs; SHIFT+SPACE writes Marked.xml. " % SOLO_SECONDS))

    def base_of(el):
        f = el.getAttribute("file").replace("\\\\", "\\")
        return re.split(r"[\\/]", f)[-1].lower()

    # Written in play order. Review mode sorts at runtime regardless, so this
    # changes nothing functionally -- it just means the file reads the way it
    # runs instead of in Komplett.xml's grouping.
    scenes = sorted(scenes, key=base_of)

    seen, n = set(), 0
    for el in scenes:
        f = el.getAttribute("file")
        base = re.split(r"[\\/]", f.replace("\\\\", "\\"))[-1]
        if base in seen:
            continue
        seen.add(base)
        copy = out.importNode(el, True)
        copy.setAttribute("probability", "1.0")
        copy.setAttribute("minTimeSolo", str(SOLO_SECONDS))
        copy.setAttribute("maxTimeSolo", str(SOLO_SECONDS))
        copy.setAttribute("minTimeInterpolation", str(FADE_SECONDS))
        copy.setAttribute("maxTimeInterpolation", str(FADE_SECONDS))
        cfg.appendChild(copy)
        n += 1

    # Plain overlay only: the point is to see the SCENE.
    comb = out.createElement("CombineShader")
    for k, v in (("file", "..\\FX\\FxPlain.frag"), ("type", "normal"),
                 ("probability", "1.0"), ("complexity", "1"),
                 ("minTimeSolo", "3600"), ("maxTimeSolo", "3601"),
                 ("minTimeInterpolation", "1"), ("maxTimeInterpolation", "1")):
        comb.setAttribute(k, v)
    cfg.appendChild(comb)

    # One neutral transition: without any entry the engine warns and falls back,
    # and a styled transition would be one more thing painting over the scene.
    tr = out.createElement("TransitionShader")
    for k, v in (("file", "..\\Transitions\\Crossfade.frag"), ("type", "normal"),
                 ("probability", "1"), ("complexity", "1")):
        tr.setAttribute(k, v)
    cfg.appendChild(tr)

    xml = out.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")
    xml = "\n".join(l for l in xml.split("\n") if l.strip())
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(xml + "\n")

    # Refuse to ship something the loader would choke on.
    try:
        minidom.parse(out_path)
    except Exception as e:
        print("generated file does not parse: %s" % e)
        return 1

    print("%s: %d scenes, %d s each, FxPlain only" % (out_path, n, SOLO_SECONDS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
