r"""Build a review harness config holding every scene that matches a filter.

Reviewing a large catalogue by watching it is hopeless: the scheduler picks
scenes at random by design, so seeing all N by chance takes several times the
catalogue's length and still leaves gaps. Pair the config this writes with
KALEIDO_SCENE_SWEEP=<seconds>, which walks the list in order, and every scene
lands at a predictable timestamp in the recording.

  python Tools/make_sweep_config.py                 # every geom="mesh" scene
  python Tools/make_sweep_config.py --match Ship    # only scenes whose shader matches
  python Tools/make_sweep_config.py --hold 10       # longer hold per scene

Then, from Release\:
  set KALEIDO_SCENE_SWEEP=6
  Kaleidoscope.exe -c MeshSweep -x <wav> -l -t 0
"""
import argparse, io, os, re, sys

ap = argparse.ArgumentParser()
ap.add_argument("--source", default="Configurations/Komplett.xml")
ap.add_argument("--out",    default="Configurations/MeshSweep.xml")
ap.add_argument("--name",   default="MeshSweep")
ap.add_argument("--filter", default='geom="mesh"',
                help='substring the opening tag must contain')
ap.add_argument("--match",  default=None,
                help="extra substring filter on the opening tag (e.g. a shader name)")
ap.add_argument("--hold",   type=int, default=6,
                help="seconds per scene; pass the same value in KALEIDO_SCENE_SWEEP")
a = ap.parse_args()

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
src = io.open(a.source, encoding="utf-8").read()

blocks = []
for m in re.finditer(r'<TextureShader\b[^>]*?>', src):
    head = m.group(0)
    if a.filter not in head:            continue
    if a.match and a.match not in head: continue
    end = src.index("</TextureShader>", m.start()) + len("</TextureShader>")
    blocks.append(src[m.start():end])

if not blocks:
    sys.exit("no scene matched -- nothing to write")

out = []
for b in blocks:
    cut = b.index(">")
    head, rest = b[:cut], b[cut:]
    head = re.sub(r'\s*probability="[^"]*"', '', head)
    head = re.sub(r'\s*(min|max)Time(Solo|Interpolation)="[^"]*"', '', head)
    # Hold == the sweep interval, so a scene staged on sceneProgress runs its
    # whole 0..1 arc inside its window. The 1 s fade matters just as much: the
    # catalogue default is 15-50 s, which would leave the recording showing
    # almost nothing but cross-fades between neighbours.
    head += (' probability="1.0" minTimeSolo="%d" maxTimeSolo="%d"'
             ' minTimeInterpolation="1" maxTimeInterpolation="2"' % (a.hold, a.hold + 1))
    out.append(head + rest)

hdr = ('<?xml version="1.0" encoding="utf-8" ?>\n'
       '<configuration ImageDirectory="C:\\Users\\rene\\Desktop\\BilderPhotoechoes"'
       ' ConfigurationName="%s" hidden="true" >\n\n'
       '  <!-- GENERATED by Tools/make_sweep_config.py -- do not hand-edit.\n'
       '       Every matching scene, in catalogue order, for review with\n'
       '       KALEIDO_SCENE_SWEEP=%d. hidden="true" keeps it out of the\n'
       '       user-facing preset list; -c %s still loads it. -->\n\n'
       % (a.name, a.hold, a.name))
io.open(a.out, "w", encoding="utf-8").write(hdr + "\n".join(out) + "\n\n</configuration>\n")
print("%s: %d scenes, %d s each (%d s total)"
      % (a.out, len(out), a.hold, len(out) * a.hold))
