/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

/**
 * @file mainwindow.h
 * @brief Qt-uic-generated layout for the main window: builds and lays out the
 *        menu actions and the central GLwidget. Regenerated from mainwindow.ui;
 *        do not hand-edit its structure (see the WARNING comment above).
 */
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "glwidget.h"

QT_BEGIN_NAMESPACE

/**
 * @brief Generated widget layout for the main window (from mainwindow.ui).
 *
 * Holds the menu QAction objects (Exit, Open Model, Reload) and the central
 * layout that hosts the single GLwidget filling the window. Instantiated via
 * the Ui::MainWindow alias below and driven through setupUi()/retranslateUi().
 */
class Ui_MainWindow
{
public:
    QAction *actionExit;         ///< "Exit" menu action; QMyWindow connects this to slotQuitApp().
    QAction *actionOpenModel;    ///< "Open Model" menu action (declared by the .ui; wiring lives elsewhere).
    QAction *actionReload;       ///< "Reload" menu action (declared by the .ui; wiring lives elsewhere).
    QWidget *centralwidget;      ///< Central widget of the main window, hosting the layouts below.
    QVBoxLayout *verticalLayout; ///< Outer vertical layout of centralwidget (zero margins/spacing).
    QHBoxLayout *hboxLayout;     ///< Inner horizontal layout that contains the GLwidget.
    GLwidget *widget;            ///< The embedded OpenGL render widget that fills the window.

    /**
     * @brief Builds and lays out all widgets/actions of the main window and
     *        installs the GLwidget as the central widget's content.
     * @param MainWindow The QMainWindow instance to populate.
     */
    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(702, 680);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName("actionExit");
        actionOpenModel = new QAction(MainWindow);
        actionOpenModel->setObjectName("actionOpenModel");
        actionReload = new QAction(MainWindow);
        actionReload->setObjectName("actionReload");
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        verticalLayout = new QVBoxLayout(centralwidget);
        verticalLayout->setSpacing(0);
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        verticalLayout->setObjectName("verticalLayout");
        hboxLayout = new QHBoxLayout();
        hboxLayout->setSpacing(0);
#ifndef Q_OS_MAC
        hboxLayout->setContentsMargins(0, 0, 0, 0);
#endif
        hboxLayout->setObjectName("hboxLayout");
        widget = new GLwidget(centralwidget);
        widget->setObjectName("widget");
        QSizePolicy sizePolicy(QSizePolicy::Policy::Expanding, QSizePolicy::Policy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(widget->sizePolicy().hasHeightForWidth());
        widget->setSizePolicy(sizePolicy);

        hboxLayout->addWidget(widget);


        verticalLayout->addLayout(hboxLayout);

        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    /**
     * @brief Sets the translated text of the window title and every menu action.
     *        Called once from setupUi(); would be called again on a language change.
     * @param MainWindow The QMainWindow instance whose strings are (re)applied.
     */
    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        actionExit->setText(QCoreApplication::translate("MainWindow", "Exit", nullptr));
        actionOpenModel->setText(QCoreApplication::translate("MainWindow", "Open Model", nullptr));
        actionReload->setText(QCoreApplication::translate("MainWindow", "Reload", nullptr));
    } // retranslateUi

};

namespace Ui {
    /**
     * @brief Project-facing alias for Ui_MainWindow, as generated by uic.
     *
     * QMyWindow holds one as `m_ui` and calls `m_ui.setupUi(this)`; this is the
     * conventional Qt Designer indirection so hand-written code refers to
     * `Ui::MainWindow` regardless of the generated class name.
     */
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // MAINWINDOW_H
